"""Что лежит в лавке клуба: сами вещи, по одной записи на предмет.

Здесь только содержимое — числа, названия и картинки. Правила, по которым
предмет работает в бою, живут в `bot.game.gear`, а всё остальное берёт и
то и другое из `bot.game.equipment`: добавляя вещь, править нужно только
этот файл.

Товар открывается уровнем: с 4-го идёт оружие, с 5-го — куртки, штаны,
наручи и пояса, с 6-го обновляется оружие и приходят головные уборы с
обувью, с 7-го — оружие, перчатки и щиты, с 8-го — последнее оружие.
В каждом наборе есть вещь под каждый класс, но кредитов на всё не хватит:
на уровень капает около сотни, а набор стоит втрое дороже — в этом и
развилка.

Границы, за которые содержимому выходить нельзя, держит
`tests/test_content.py`: полоса процентов, лестница урона и плоских
прибавок, выносливости на вещах нет. Новая вещь проходит этот тест —
значит, она не ломает баланс классов.

Проценты живут на оружии и идут полосой: 10–15% на пятом уровне, 45–50%
на десятом. Каждое оружие несёт свою долю и ответ той паре, которой его
класс держит удар: уворот сбивается точностью, крит — антикритом, и в бою
они вычитаются. Нападение берёт низ полосы, ответ — верх: у нападения уже
есть фора от характеристики класса.

Картинка обычно не указывается: вещь получает адрес от своего кода —
`items/<code>.jpeg`. Строка `image=` осталась у старых файлов, чьи имена
под это правило не подходят.
"""

from __future__ import annotations

from dataclasses import replace

from bot.game import art
from bot.game.classes import Stats
from bot.game.gear import ALL_SLOTS, RING_SLOTS, Item, ItemKind, Slot

# Папки картинок в R2: у старых файлов адрес задан явно
ART = art.BUCKET
WEAPON_ART = art.WEAPONS
ADDED_ART = art.ADDED
ITEM_ART = art.ITEMS
MAGIC_ART = art.MAGIC

WARRIOR, ROGUE, ASSASSIN, TANK = "warrior", "rogue", "assassin", "tank"

# Прилавок фанатского магазина на Северном Валу: свой товар, своя цена и
# своя лестница. Пустой `shelf` — товар клубной лавки
FAN_SHELF = "fan"

# ---------- сеты клубной лавки: шестнадцать наборов на четыре класса ----------
#
# Второй заход по одежде: вместо россыпи отдельных вещей — наборы. Четыре
# линии по классам (`avenger/boxer/army/bouncer` у танка, `plut/croupier/
# lovkach/cardsharp` у трикстера, `mercenary/strangler/camouflage/killer` у
# ассасина, `sport/biker/fighter/hero` у воина), в каждой линии четыре
# ступени, в ступени — вещи на свои слоты.
#
# Лестница у пака своя и идёт слотами: на втором уровне открываются голова,
# куртка и обувь, на третьем — футболка и штаны, на четвёртом — пояс,
# перчатки и обувь, и так до девятого. Цена растёт с уровнем: 60 кредитов
# на втором, 500 на девятом — пять уровней дохода за вещь.
#
# Проценты здесь крупные и это главное, что вещь даёт: полосу по уровню
# держит `gear_share_cap`. Пары разведены по классам, как и на оружии:
# танку антикрит, трикстеру уворот с контрударом, ассасину крит с
# точностью, воину — всё по чуть-чуть, потому что воин в круге не стоит.
#
# Одно число из присланного пака здесь изменено, и вот какое: танку в нём
# была написана ещё и точность — 25% на девятой ступени, по 5–10% ниже.
# Точность сбивает уворот, то есть она и есть ответ трикстеру, а трикстер
# в круге бьёт танка. С ней круг переворачивался: трикстер брал у танка
# 17% вместо 96%, и ломало его именно это, а не запас здоровья танка
# (с урезанным на 40% запасом те же 18%). Поэтому точность с девяти
# танковых вещей снята, остальные числа пака — как присланы. Танку
# взамен не добавлено ничего: его набор и так самый тяжёлый в лавке —
# 310 единиц запаса против 135 у трикстера.
#
# Старую одежду пак обошёл по всем слотам, поэтому с витрины она ушла
# (`RETIRED_GEAR` ниже). Из каталога она не ушла: у кого куплена, у того и
# осталась.

# Папка картинок у пака своя, и линия класса в ней зовётся по-своему:
# трикстер лежит в `trickster`, хотя класс в коде — `rogue`
SET_LINES = {TANK: "tank", ROGUE: "trickster", ASSASSIN: "assassin", WARRIOR: "warrior"}


def _piece(
    kit: str,
    slot: Slot,
    icon: str,
    title: str,
    fclass: str,
    level: int,
    price: int,
    requires: Stats,
    **gives: int | float,
) -> Item:
    """Вещь из набора: код и картинка считаются от набора и слота.

    Код с приставкой `set_` нарочно: половина наборов названа так же, как
    старые вещи лавки (`bouncer`, `cardsharp`, `army`, `biker`), а код
    вещи лежит в базе у каждого, кто её купил. Приставка разводит новое
    со старым, не трогая ни одной купленной вещи.
    """
    return Item(
        f"set_{kit}_{slot.value}",
        title,
        slot,
        icon,
        image=art.set_piece(SET_LINES[fclass], kit, slot.value),
        level_required=level,
        requires=requires,
        price=price,
        for_classes=(fclass,),
        **gives,
    )


SET_PIECES: tuple[Item, ...] = (
    # head
    _piece(
        'avenger', Slot.HEAD, '🧢', 'Бандана мстителя',
        TANK, 2, 60, Stats(endurance=6),
        strength=1, armor_min=2, armor_max=3, anticrit=0.05,
    ),
    _piece(
        'mercenary', Slot.HEAD, '🧢', 'Бандана наёмника',
        ASSASSIN, 2, 60, Stats(intuition=6),
        intuition=1, armor_min=2, armor_max=3, crit=0.05,
    ),
    _piece(
        'plut', Slot.HEAD, '🧢', 'Бандана плута',
        ROGUE, 2, 60, Stats(agility=6),
        agility=1, armor_min=2, armor_max=3, dodge=0.05,
    ),
    _piece(
        'sport', Slot.HEAD, '🧢', 'Спортивная бандана',
        WARRIOR, 2, 60, Stats(strength=6),
        strength=1, hp=15, armor_min=2, armor_max=3,
    ),
    _piece(
        'biker', Slot.HEAD, '🧢', 'Байкерский мотошлем',
        WARRIOR, 5, 100, Stats(strength=15),
        strength=1, hp=15, armor_min=5, armor_max=7, dodge=0.05, crit=0.05, anticrit=0.05,
    ),
    _piece(
        'boxer', Slot.HEAD, '🧢', 'Боксёрский шлем',
        TANK, 5, 100, Stats(endurance=15),
        strength=1, hp=15, armor_min=5, armor_max=7, anticrit=0.15,
    ),
    _piece(
        'croupier', Slot.HEAD, '🧢', 'Козырёк крупье',
        ROGUE, 5, 100, Stats(agility=15),
        agility=1, hp=10, armor_min=4, armor_max=6, dodge=0.15,
    ),
    _piece(
        'strangler', Slot.HEAD, '🧢', 'Балаклава душителя',
        ASSASSIN, 5, 100, Stats(intuition=15),
        intuition=1, hp=10, armor_min=4, armor_max=6, crit=0.15,
    ),
    _piece(
        'army', Slot.HEAD, '🧢', 'Армейская каска',
        TANK, 7, 300, Stats(endurance=20),
        strength=2, hp=30, armor_min=8, armor_max=10, anticrit=0.2,
    ),
    _piece(
        'camouflage', Slot.HEAD, '🧢', 'Камуфляжная каска',
        ASSASSIN, 7, 300, Stats(intuition=20),
        intuition=2, hp=15, armor_min=7, armor_max=9, crit=0.2,
    ),
    _piece(
        'fighter', Slot.HEAD, '🧢', 'Укреплённый шлем бойца',
        WARRIOR, 7, 300, Stats(strength=20),
        strength=2, hp=25, armor_min=8, armor_max=10, dodge=0.1, crit=0.1, anticrit=0.1,
    ),
    _piece(
        'lovkach', Slot.HEAD, '🧢', 'Лёгкий шлем ловкача',
        ROGUE, 7, 300, Stats(agility=20),
        agility=2, hp=15, armor_min=7, armor_max=9, dodge=0.2,
    ),
    _piece(
        'bouncer', Slot.HEAD, '🧢', 'Усиленный шлем вышибалы',
        TANK, 9, 500, Stats(endurance=25),
        strength=4, hp=60, armor_min=11, armor_max=13, anticrit=0.4,
    ),
    _piece(
        'cardsharp', Slot.HEAD, '🧢', 'Шлем шулера',
        ROGUE, 9, 500, Stats(agility=25),
        agility=4, hp=20, armor_min=9, armor_max=11, dodge=0.4, counter=0.25,
    ),
    _piece(
        'hero', Slot.HEAD, '🧢', 'Шлем героя',
        WARRIOR, 9, 500, Stats(strength=25, endurance=20),
        strength=2, agility=1, intuition=1, hp=45, armor_min=10, armor_max=12, accuracy=0.2, dodge=0.2, crit=0.2, anticrit=0.2,
    ),
    _piece(
        'killer', Slot.HEAD, '🧢', 'Шлем убийцы',
        ASSASSIN, 9, 500, Stats(intuition=25),
        intuition=4, hp=20, armor_min=9, armor_max=11, accuracy=0.25, crit=0.4,
    ),
    # shirt
    _piece(
        'avenger', Slot.SHIRT, '👕', 'Футболка мстителя',
        TANK, 3, 70, Stats(endurance=12),
        strength=2, agility=1, intuition=1, hp=15,
    ),
    _piece(
        'mercenary', Slot.SHIRT, '👕', 'Футболка наёмника',
        ASSASSIN, 3, 70, Stats(intuition=12),
        strength=1, agility=1, intuition=2, hp=10,
    ),
    _piece(
        'plut', Slot.SHIRT, '👕', 'Футболка плута',
        ROGUE, 3, 70, Stats(agility=12),
        strength=1, agility=2, intuition=1, hp=10,
    ),
    _piece(
        'sport', Slot.SHIRT, '👕', 'Спортивная футболка',
        WARRIOR, 3, 70, Stats(strength=12),
        strength=2, agility=1, intuition=1, hp=10,
    ),
    _piece(
        'army', Slot.SHIRT, '👕', 'Кевларовая армейская футболка',
        TANK, 6, 200, Stats(endurance=17),
        strength=2, agility=2, intuition=2, hp=60,
    ),
    _piece(
        'camouflage', Slot.SHIRT, '👕', 'Камуфляжная футболка',
        ASSASSIN, 6, 200, Stats(intuition=17),
        strength=2, agility=2, intuition=4, hp=20,
    ),
    _piece(
        'fighter', Slot.SHIRT, '👕', 'Компрессионная футболка бойца',
        WARRIOR, 6, 200, Stats(strength=17),
        strength=4, agility=2, intuition=2, hp=20,
    ),
    _piece(
        'lovkach', Slot.SHIRT, '👕', 'Футболка ловкача',
        ROGUE, 6, 200, Stats(agility=17),
        strength=2, agility=4, intuition=2, hp=20,
    ),
    # belt
    _piece(
        'biker', Slot.BELT, '🥋', 'Байкерский пояс',
        WARRIOR, 4, 80, Stats(strength=13),
        strength=1, armor_min=4, armor_max=6, crit=0.1, anticrit=0.05,
    ),
    _piece(
        'boxer', Slot.BELT, '🥋', 'Боксёрский пояс',
        TANK, 4, 80, Stats(endurance=13),
        hp=10, armor_min=4, armor_max=6, anticrit=0.1,
    ),
    _piece(
        'croupier', Slot.BELT, '🥋', 'Строгий пояс крупье',
        ROGUE, 4, 80, Stats(agility=13),
        agility=1, armor_min=3, armor_max=5, dodge=0.1, anticrit=0.05,
    ),
    _piece(
        'strangler', Slot.BELT, '🥋', 'Пояс душителя',
        ASSASSIN, 4, 80, Stats(intuition=13),
        intuition=1, armor_min=3, armor_max=5, accuracy=0.05, crit=0.1,
    ),
    _piece(
        'bouncer', Slot.BELT, '🥋', 'Усиленный пояс вышибалы',
        TANK, 8, 400, Stats(endurance=22),
        strength=2, agility=1, intuition=1, hp=25, armor_min=10, armor_max=12, anticrit=0.3,
    ),
    _piece(
        'cardsharp', Slot.BELT, '🥋', 'Пояс шулера',
        ROGUE, 8, 400, Stats(agility=22),
        strength=1, agility=3, hp=15, armor_min=8, armor_max=10, dodge=0.3, anticrit=0.2,
    ),
    _piece(
        'hero', Slot.BELT, '🥋', 'Пояс героя',
        WARRIOR, 8, 400, Stats(strength=22),
        strength=2, agility=1, intuition=1, hp=20, armor_min=9, armor_max=11, accuracy=0.15, dodge=0.15, crit=0.15, anticrit=0.05,
    ),
    _piece(
        'killer', Slot.BELT, '🥋', 'Пояс убийцы',
        ASSASSIN, 8, 400, Stats(intuition=22),
        strength=1, intuition=3, hp=15, armor_min=8, armor_max=10, accuracy=0.2, crit=0.3,
    ),
    # gloves
    _piece(
        'biker', Slot.GLOVES, '🧤', 'Байкерские перчатки',
        WARRIOR, 4, 80, Stats(strength=13),
        strength=1, dodge=0.05, crit=0.05, anticrit=0.05,
    ),
    _piece(
        'boxer', Slot.GLOVES, '🧤', 'Боксёрские перчатки',
        TANK, 4, 80, Stats(endurance=13),
        strength=1, hp=15, anticrit=0.15,
    ),
    _piece(
        'croupier', Slot.GLOVES, '🧤', 'Перчатки крупье',
        ROGUE, 4, 80, Stats(agility=13),
        agility=1, dodge=0.15,
    ),
    _piece(
        'strangler', Slot.GLOVES, '🧤', 'Перчатки душителя',
        ASSASSIN, 4, 80, Stats(intuition=13),
        intuition=1, crit=0.15,
    ),
    _piece(
        'bouncer', Slot.GLOVES, '🧤', 'Боевые перчатки вышибалы',
        TANK, 9, 500, Stats(endurance=25),
        strength=4, agility=1, intuition=1, hp=20, anticrit=0.4,
    ),
    _piece(
        'cardsharp', Slot.GLOVES, '🧤', 'Перчатки шулера',
        ROGUE, 9, 500, Stats(agility=25),
        strength=2, agility=4, hp=10, accuracy=0.2, dodge=0.4,
    ),
    _piece(
        'hero', Slot.GLOVES, '🧤', 'Перчатки героя',
        WARRIOR, 9, 500, Stats(strength=25, endurance=20),
        strength=2, agility=2, intuition=2, hp=15, accuracy=0.2, dodge=0.2, crit=0.2,
    ),
    _piece(
        'killer', Slot.GLOVES, '🧤', 'Перчатки убийцы',
        ASSASSIN, 9, 500, Stats(intuition=25),
        strength=2, intuition=4, hp=10, accuracy=0.2, crit=0.4,
    ),
    # jacket
    _piece(
        'avenger', Slot.JACKET, '🧥', 'Куртка мстителя',
        TANK, 2, 60, Stats(endurance=6),
        strength=1, armor_min=2, armor_max=3, anticrit=0.05,
    ),
    _piece(
        'mercenary', Slot.JACKET, '🧥', 'Куртка наёмника',
        ASSASSIN, 2, 60, Stats(intuition=6),
        intuition=1, armor_min=2, armor_max=3, crit=0.05,
    ),
    _piece(
        'plut', Slot.JACKET, '🧥', 'Куртка плута',
        ROGUE, 2, 60, Stats(agility=6),
        agility=1, armor_min=2, armor_max=3, dodge=0.05,
    ),
    _piece(
        'sport', Slot.JACKET, '🧥', 'Спортивная куртка',
        WARRIOR, 2, 60, Stats(strength=6),
        strength=1, hp=15, armor_min=2, armor_max=3,
    ),
    _piece(
        'biker', Slot.JACKET, '🧥', 'Байкерская куртка',
        WARRIOR, 5, 100, Stats(strength=15),
        strength=1, hp=15, armor_min=5, armor_max=7, dodge=0.05, crit=0.05, anticrit=0.05,
    ),
    _piece(
        'boxer', Slot.JACKET, '🧥', 'Боксёрская защитная куртка',
        TANK, 5, 100, Stats(endurance=15),
        strength=1, hp=30, armor_min=5, armor_max=7, anticrit=0.15,
    ),
    _piece(
        'croupier', Slot.JACKET, '🧥', 'Куртка крупье',
        ROGUE, 5, 100, Stats(agility=15),
        agility=1, hp=10, armor_min=4, armor_max=6, dodge=0.15,
    ),
    _piece(
        'strangler', Slot.JACKET, '🧥', 'Плащ душителя',
        ASSASSIN, 5, 100, Stats(intuition=15),
        intuition=1, hp=10, armor_min=4, armor_max=6, crit=0.15,
    ),
    _piece(
        'army', Slot.JACKET, '🧥', 'Армейская куртка',
        TANK, 7, 200, Stats(endurance=20),
        strength=2, hp=60, armor_min=8, armor_max=10, anticrit=0.2,
    ),
    _piece(
        'camouflage', Slot.JACKET, '🧥', 'Камуфляжная куртка',
        ASSASSIN, 7, 200, Stats(intuition=20),
        intuition=2, hp=30, armor_min=7, armor_max=9, crit=0.2,
    ),
    _piece(
        'fighter', Slot.JACKET, '🧥', 'Кожаная куртка бойца',
        WARRIOR, 7, 200, Stats(strength=20),
        strength=2, hp=50, armor_min=8, armor_max=10, dodge=0.1, crit=0.1, anticrit=0.1,
    ),
    _piece(
        'lovkach', Slot.JACKET, '🧥', 'Лёгкая куртка ловкача',
        ROGUE, 7, 200, Stats(agility=20),
        agility=2, hp=30, armor_min=7, armor_max=9, dodge=0.2,
    ),
    _piece(
        'bouncer', Slot.JACKET, '🧥', 'Бронекуртка вышибалы',
        TANK, 9, 500, Stats(endurance=25),
        strength=4, agility=2, intuition=2, hp=75, armor_min=12, armor_max=14, anticrit=0.4,
    ),
    _piece(
        'cardsharp', Slot.JACKET, '🧥', 'Куртка шулера',
        ROGUE, 9, 500, Stats(agility=25),
        strength=2, agility=4, intuition=2, hp=40, armor_min=10, armor_max=12, dodge=0.4, counter=0.25,
    ),
    _piece(
        'hero', Slot.JACKET, '🧥', 'Куртка героя',
        WARRIOR, 9, 500, Stats(strength=25, endurance=20),
        strength=4, agility=2, intuition=2, hp=60, armor_min=11, armor_max=13, accuracy=0.2, dodge=0.2, crit=0.2, anticrit=0.2,
    ),
    _piece(
        'killer', Slot.JACKET, '🧥', 'Куртка убийцы',
        ASSASSIN, 9, 500, Stats(intuition=25),
        strength=2, agility=2, intuition=4, hp=40, armor_min=10, armor_max=12, accuracy=0.25, crit=0.4,
    ),
    # pants
    _piece(
        'avenger', Slot.PANTS, '👖', 'Штаны мстителя',
        TANK, 3, 70, Stats(endurance=12),
        hp=15, armor_min=3, armor_max=4, anticrit=0.1,
    ),
    _piece(
        'mercenary', Slot.PANTS, '👖', 'Штаны наёмника',
        ASSASSIN, 3, 70, Stats(intuition=12),
        intuition=1, armor_min=3, armor_max=4, crit=0.05, anticrit=0.05,
    ),
    _piece(
        'plut', Slot.PANTS, '👖', 'Штаны плута',
        ROGUE, 3, 70, Stats(agility=12),
        agility=1, armor_min=3, armor_max=4, accuracy=0.05, dodge=0.05,
    ),
    _piece(
        'sport', Slot.PANTS, '👖', 'Спортивные штаны',
        WARRIOR, 3, 70, Stats(strength=12),
        armor_min=3, armor_max=4, accuracy=0.05, dodge=0.05, crit=0.05, anticrit=0.05,
    ),
    _piece(
        'biker', Slot.PANTS, '👖', 'Байкерские штаны',
        WARRIOR, 5, 100, Stats(strength=15),
        strength=1, hp=15, armor_min=5, armor_max=7, dodge=0.05, crit=0.05, anticrit=0.05,
    ),
    _piece(
        'boxer', Slot.PANTS, '👖', 'Боксёрские тренировочные штаны',
        TANK, 5, 100, Stats(endurance=15),
        strength=1, hp=15, armor_min=5, armor_max=7, anticrit=0.15,
    ),
    _piece(
        'croupier', Slot.PANTS, '👖', 'Штаны крупье',
        ROGUE, 5, 100, Stats(agility=15),
        agility=1, hp=10, armor_min=4, armor_max=6, dodge=0.15,
    ),
    _piece(
        'strangler', Slot.PANTS, '👖', 'Брюки душителя',
        ASSASSIN, 5, 100, Stats(intuition=15),
        intuition=1, hp=10, armor_min=4, armor_max=6, crit=0.15,
    ),
    _piece(
        'bouncer', Slot.PANTS, '👖', 'Усиленные штаны вышибалы',
        TANK, 8, 400, Stats(endurance=22),
        strength=2, agility=2, intuition=2, hp=40, armor_min=10, armor_max=12, anticrit=0.3,
    ),
    _piece(
        'cardsharp', Slot.PANTS, '👖', 'Брюки шулера',
        ROGUE, 8, 400, Stats(agility=22),
        strength=3, agility=3, hp=20, armor_min=8, armor_max=10, dodge=0.3, anticrit=0.2,
    ),
    _piece(
        'hero', Slot.PANTS, '👖', 'Брюки героя',
        WARRIOR, 8, 400, Stats(strength=22),
        strength=3, agility=1, intuition=1, hp=30, armor_min=9, armor_max=11, accuracy=0.15, dodge=0.15, crit=0.15, anticrit=0.05,
    ),
    _piece(
        'killer', Slot.PANTS, '👖', 'Штаны убийцы',
        ASSASSIN, 8, 400, Stats(intuition=22),
        strength=3, intuition=3, hp=20, armor_min=8, armor_max=10, accuracy=0.2, crit=0.3,
    ),
    # boots
    _piece(
        'avenger', Slot.BOOTS, '👟', 'Кеды мстителя',
        TANK, 2, 60, Stats(endurance=6),
        strength=1, armor_min=2, armor_max=3, anticrit=0.05,
    ),
    _piece(
        'mercenary', Slot.BOOTS, '👟', 'Кеды наёмника',
        ASSASSIN, 2, 60, Stats(intuition=6),
        intuition=1, armor_min=2, armor_max=3, crit=0.05,
    ),
    _piece(
        'plut', Slot.BOOTS, '👟', 'Кеды плута',
        ROGUE, 2, 60, Stats(agility=6),
        agility=1, armor_min=2, armor_max=3, dodge=0.05,
    ),
    _piece(
        'sport', Slot.BOOTS, '👟', 'Спортивные кеды',
        WARRIOR, 2, 60, Stats(strength=6),
        strength=1, hp=15, armor_min=2, armor_max=3,
    ),
    _piece(
        'biker', Slot.BOOTS, '👟', 'Байкерские кроссовки',
        WARRIOR, 4, 80, Stats(strength=13),
        strength=1, hp=10, armor_min=4, armor_max=6, crit=0.1, anticrit=0.05,
    ),
    _piece(
        'boxer', Slot.BOOTS, '👟', 'Боксёрские кроссовки',
        TANK, 4, 80, Stats(endurance=13),
        hp=10, armor_min=4, armor_max=6, anticrit=0.05,
    ),
    _piece(
        'croupier', Slot.BOOTS, '👟', 'Лёгкие ботинки крупье',
        ROGUE, 4, 80, Stats(agility=13),
        agility=1, hp=10, armor_min=3, armor_max=5, dodge=0.1, anticrit=0.05,
    ),
    _piece(
        'strangler', Slot.BOOTS, '👟', 'Кроссовки душителя',
        ASSASSIN, 4, 80, Stats(intuition=13),
        intuition=1, hp=10, armor_min=3, armor_max=5, accuracy=0.05, crit=0.1,
    ),
    _piece(
        'army', Slot.BOOTS, '👟', 'Армейские ботинки',
        TANK, 6, 200, Stats(endurance=17),
        strength=1, hp=20, armor_min=7, armor_max=9, anticrit=0.15,
    ),
    _piece(
        'camouflage', Slot.BOOTS, '👟', 'Камуфляжные берцы',
        ASSASSIN, 6, 200, Stats(intuition=17),
        intuition=1, hp=10, armor_min=6, armor_max=8, crit=0.15, anticrit=0.05,
    ),
    _piece(
        'fighter', Slot.BOOTS, '👟', 'Кожаные берцы бойца',
        WARRIOR, 6, 200, Stats(strength=17),
        strength=1, hp=15, armor_min=7, armor_max=9, accuracy=0.05, dodge=0.05, crit=0.05, anticrit=0.05,
    ),
    _piece(
        'lovkach', Slot.BOOTS, '👟', 'Лёгкие берцы ловкача',
        ROGUE, 6, 200, Stats(agility=17),
        agility=1, hp=10, armor_min=6, armor_max=8, accuracy=0.05, dodge=0.15,
    ),
    _piece(
        'bouncer', Slot.BOOTS, '👟', 'Усиленные ботинки вышибалы',
        TANK, 9, 500, Stats(endurance=25),
        strength=4, hp=30, armor_min=11, armor_max=13, anticrit=0.4,
    ),
    _piece(
        'cardsharp', Slot.BOOTS, '👟', 'Лёгкие сапоги шулера',
        ROGUE, 9, 500, Stats(agility=25),
        agility=4, hp=10, armor_min=9, armor_max=11, accuracy=0.25, dodge=0.4,
    ),
    _piece(
        'hero', Slot.BOOTS, '👟', 'Берцы героя',
        WARRIOR, 9, 500, Stats(strength=25, endurance=20),
        strength=2, agility=1, intuition=1, hp=25, armor_min=10, armor_max=12, accuracy=0.2, dodge=0.2, crit=0.2, anticrit=0.2,
    ),
    _piece(
        'killer', Slot.BOOTS, '👟', 'Камуфляжные ботинки убийцы',
        ASSASSIN, 9, 500, Stats(intuition=25),
        intuition=4, hp=10, armor_min=9, armor_max=11, crit=0.4, anticrit=0.25,
    ),
)

# ---------- прилавок ювелира: кольца и ожерелья ----------
#
# Украшения продаются только здесь: ни в клубной лавке, ни у одёжника их
# не бывает — слоты под них у бойца есть с самого начала, а товара не
# было вовсе. Прилавок свой, как у «Северного Вала»: в витрину клуба он
# не входит и эталонного бойца за собой не тянет — круг классов считается
# по клубной лестнице, и украшения его не перекашивают.
#
# Товар двух видов, и это те самые две полки: ожерелья и кольца.
#
# Ожерелье идёт линиями наборов — по вещи на ступень на каждый класс, от
# третьего уровня до девятого, цена от 70 до 500 кредитов. Проценты на
# нём крупные, как у сетов, и держит их та же полоса `gear_share_cap`:
# 20% на третьем уровне, 80% на девятом. Броня есть на старших кулонах —
# и прикрывает она, как у щита, все зоны сразу.
#
# Кольца тоже идут линиями, но мельче: одна доля на вещь. Зато носить их
# можно сразу три, и в этом вся их цена: 20 кредитов за простое кольцо
# первого уровня, 200 — за кольцо девятого. Четыре простых кольца
# открывают игру (сила, ловкость, интуиция, жизни), три сильных её
# закрывают. У «кольца защиты» есть и броня — тоже на все зоны, и в три
# клетки она складывается втрое. Так решил владелец; удар броня всё
# равно гасит не больше чем на `MAX_ARMOR_SHARE`, и бесконечным бой от
# трёх колец не становится.
#
# Числа у всех украшений — как присланы.
JEWEL_SHELF = "jewel"


def _jewel(
    kit: str,
    slot: Slot,
    title: str,
    fclass: str,
    level: int,
    price: int,
    requires: Stats,
    **gives: int | float,
) -> Item:
    """Украшение из линии набора: своя клетка, свой прилавок.

    Картинка лежит рядом с остальным набором, но под именем украшения, а
    не под кодом клетки: кольцо в линии одно, а клеток под него три, и
    `ring_right.png` в бакете никто не рисовал.
    """
    worn = "ring" if slot in RING_SLOTS else slot.value
    return Item(
        f"set_{kit}_{worn}",
        title,
        slot,
        image=art.set_piece(SET_LINES[fclass], kit, worn),
        level_required=level,
        requires=requires,
        price=price,
        for_classes=(fclass,),
        shelf=JEWEL_SHELF,
        **gives,
    )


def _plain_ring(
    code: str,
    kit: str,
    picture: str,
    title: str,
    level: int,
    price: int,
    requires: Stats,
    for_classes: tuple[str, ...],
    **gives: int | float,
) -> Item:
    """Кольцо вне линий: простое с первого уровня или сильное с девятого.

    Картинка приходит именем файла: партия назвала их по тому, что
    кольцо даёт (`strength.png`, `health.png`), и у «кольца баланса»
    название своё, а файл общий с партией.
    """
    return Item(
        code,
        title,
        Slot.RING_RIGHT,
        image=art.plain_ring(kit, picture),
        level_required=level,
        requires=requires,
        price=price,
        for_classes=for_classes,
        shelf=JEWEL_SHELF,
        **gives,
    )


JEWEL_PIECES: tuple[Item, ...] = (
    # ---------- кольца: простые, с первого уровня ----------
    _plain_ring(
        'ring_strength', 'starter', 'strength', 'Кольцо силы',
        1, 20, Stats(), (WARRIOR,), strength=1,
    ),
    _plain_ring(
        'ring_agility', 'starter', 'agility', 'Кольцо ловкости',
        1, 20, Stats(), (ROGUE,), agility=1,
    ),
    _plain_ring(
        'ring_intuition', 'starter', 'intuition', 'Кольцо интуиции',
        1, 20, Stats(), (ASSASSIN,), intuition=1,
    ),
    _plain_ring(
        'ring_health', 'starter', 'health', 'Кольцо жизней',
        1, 20, Stats(), (TANK,), hp=10,
    ),
    # ---------- кольца: линии наборов, со второго уровня ----------
    _jewel(
        'avenger', Slot.RING_RIGHT, 'Кольцо мстителя',
        TANK, 2, 30, Stats(endurance=6),
        anticrit=0.05,
    ),
    _jewel(
        'plut', Slot.RING_RIGHT, 'Кольцо плута',
        ROGUE, 2, 30, Stats(agility=6),
        dodge=0.05,
    ),
    _jewel(
        'mercenary', Slot.RING_RIGHT, 'Кольцо наёмника',
        ASSASSIN, 2, 30, Stats(intuition=6),
        crit=0.05,
    ),
    _jewel(
        'sport', Slot.RING_RIGHT, 'Спортивное кольцо',
        WARRIOR, 2, 30, Stats(strength=6),
        hp=15,
    ),
    _jewel(
        'boxer', Slot.RING_RIGHT, 'Боксёрское кольцо',
        TANK, 4, 50, Stats(endurance=13),
        hp=10, anticrit=0.1,
    ),
    _jewel(
        'biker', Slot.RING_RIGHT, 'Байкерская печатка',
        WARRIOR, 4, 50, Stats(strength=13),
        crit=0.1,
    ),
    _jewel(
        'croupier', Slot.RING_RIGHT, 'Кольцо крупье',
        ROGUE, 4, 50, Stats(agility=13),
        dodge=0.1,
    ),
    _jewel(
        'strangler', Slot.RING_RIGHT, 'Кольцо душителя',
        ASSASSIN, 4, 50, Stats(intuition=13),
        crit=0.1,
    ),
    _jewel(
        'army', Slot.RING_RIGHT, 'Армейское кольцо',
        TANK, 6, 80, Stats(endurance=17),
        hp=20, anticrit=0.15,
    ),
    _jewel(
        'fighter', Slot.RING_RIGHT, 'Кольцо бойца',
        WARRIOR, 6, 80, Stats(strength=17),
        accuracy=0.05, dodge=0.05, crit=0.05, anticrit=0.05,
    ),
    _jewel(
        'lovkach', Slot.RING_RIGHT, 'Кольцо ловкача',
        ROGUE, 6, 80, Stats(agility=17),
        dodge=0.15,
    ),
    _jewel(
        'camouflage', Slot.RING_RIGHT, 'Камуфляжное кольцо',
        ASSASSIN, 6, 80, Stats(intuition=17),
        crit=0.15,
    ),
    _jewel(
        'bouncer', Slot.RING_RIGHT, 'Кольцо вышибалы',
        TANK, 8, 150, Stats(endurance=22),
        anticrit=0.25,
    ),
    _jewel(
        'hero', Slot.RING_RIGHT, 'Кольцо героя',
        WARRIOR, 8, 150, Stats(strength=22),
        dodge=0.15, crit=0.15,
    ),
    _jewel(
        'cardsharp', Slot.RING_RIGHT, 'Кольцо шулера',
        ROGUE, 8, 150, Stats(agility=22),
        dodge=0.25,
    ),
    _jewel(
        'killer', Slot.RING_RIGHT, 'Кольцо убийцы',
        ASSASSIN, 8, 150, Stats(intuition=22),
        crit=0.25,
    ),
    # ---------- кольца: сильные, с девятого уровня ----------
    _plain_ring(
        'ring_balance', 'advanced', 'intuition', 'Кольцо баланса',
        9, 200, Stats(strength=20, endurance=20), (WARRIOR, TANK),
        strength=2, agility=2, intuition=2, hp=25,
    ),
    _plain_ring(
        'ring_guard', 'advanced', 'health', 'Кольцо защиты',
        9, 200, Stats(strength=20, endurance=20), (WARRIOR, TANK),
        hp=25, armor_min=5, armor_max=10,
    ),
    _plain_ring(
        'ring_luck', 'advanced', 'agility', 'Кольцо удачи',
        9, 200, Stats(intuition=20, agility=20), (ASSASSIN, ROGUE),
        dodge=0.3, crit=0.3,
    ),
    # ---------- ожерелья: линии наборов, с третьего уровня ----------
    _jewel(
        'avenger', Slot.NECKLACE, 'Ожерелье мстителя',
        TANK, 3, 70, Stats(endurance=12),
        hp=15, anticrit=0.1,
    ),
    _jewel(
        'plut', Slot.NECKLACE, 'Ожерелье плута',
        ROGUE, 3, 70, Stats(agility=12),
        agility=1, accuracy=0.05, dodge=0.05,
    ),
    _jewel(
        'mercenary', Slot.NECKLACE, 'Ожерелье наёмника',
        ASSASSIN, 3, 70, Stats(intuition=12),
        intuition=1, crit=0.05, anticrit=0.05,
    ),
    _jewel(
        'sport', Slot.NECKLACE, 'Спортивное ожерелье',
        WARRIOR, 3, 70, Stats(strength=12),
        accuracy=0.05, dodge=0.05, crit=0.05, anticrit=0.05,
    ),
    _jewel(
        'boxer', Slot.NECKLACE, 'Боксёрский кулон',
        TANK, 5, 100, Stats(endurance=15),
        strength=1, hp=15, anticrit=0.15,
    ),
    _jewel(
        'croupier', Slot.NECKLACE, 'Ожерелье крупье',
        ROGUE, 5, 100, Stats(agility=15),
        agility=1, hp=10, dodge=0.15,
    ),
    _jewel(
        'biker', Slot.NECKLACE, 'Байкерский кулон',
        WARRIOR, 5, 100, Stats(strength=15),
        strength=1, hp=15, dodge=0.05, crit=0.05, anticrit=0.05,
    ),
    _jewel(
        'strangler', Slot.NECKLACE, 'Ожерелье душителя',
        ASSASSIN, 5, 100, Stats(intuition=15),
        intuition=1, hp=10, crit=0.15,
    ),
    _jewel(
        'army', Slot.NECKLACE, 'Армейский кулон',
        TANK, 7, 200, Stats(endurance=20),
        strength=2, hp=30, anticrit=0.2,
    ),
    _jewel(
        'lovkach', Slot.NECKLACE, 'Ожерелье ловкача',
        ROGUE, 7, 200, Stats(agility=20),
        agility=2, hp=20, dodge=0.2,
    ),
    _jewel(
        'camouflage', Slot.NECKLACE, 'Камуфляжный кулон',
        ASSASSIN, 7, 200, Stats(intuition=20),
        intuition=2, hp=20, crit=0.2,
    ),
    _jewel(
        'fighter', Slot.NECKLACE, 'Кулон бойца',
        WARRIOR, 7, 200, Stats(strength=20),
        strength=2, hp=25, dodge=0.1, crit=0.1, anticrit=0.1,
    ),
    _jewel(
        'bouncer', Slot.NECKLACE, 'Кулон вышибалы',
        TANK, 9, 500, Stats(endurance=25),
        strength=4, hp=30, armor_min=11, armor_max=13, accuracy=0.25, anticrit=0.4,
    ),
    _jewel(
        'hero', Slot.NECKLACE, 'Кулон героя',
        WARRIOR, 9, 500, Stats(strength=25, endurance=20),
        strength=2, agility=1, intuition=1, hp=25, armor_min=10, armor_max=12, accuracy=0.2, dodge=0.2, crit=0.2, anticrit=0.2,
    ),
    _jewel(
        'cardsharp', Slot.NECKLACE, 'Ожерелье шулера',
        ROGUE, 9, 500, Stats(agility=25),
        agility=4, hp=10, armor_min=9, armor_max=11, accuracy=0.25, dodge=0.4,
    ),
    _jewel(
        'killer', Slot.NECKLACE, 'Кулон убийцы',
        ASSASSIN, 9, 500, Stats(intuition=25),
        intuition=4, hp=10, armor_min=9, armor_max=11, crit=0.4, anticrit=0.25,
    ),
)


# Что пак обошёл: одежда прежней лавки. На витрине её больше нет, в
# каталоге она осталась — купленное не отбирают. Оружие, щиты и майка
# сюда не входят: оружия в паке нет вовсе, щиты он не трогает, а майку
# пак переписал на месте.
RETIRED_GEAR = frozenset(
    {
        # голова
        "bandana", "moto_helmet", "visor_cap",
        # футболки
        "club_tee", "skull_tee", "rashguard", "kevlar_tee",
        # пояса
        "wide_belt", "throwing_belt", "buckle_belt", "sheath_belt",
        "cardsharp_belt", "power_belt", "knuckle_belt",
        # перчатки
        "wraps", "leather_bracers", "dealer_bracers", "battered_gloves",
        "fingerless_gloves", "card_gloves",
        # куртки
        "leather_jacket", "shadow_coat", "biker_jacket", "denim_vest",
        "cardsharp_jacket", "pit_fighter_jacket", "bouncer_armor_jacket",
        # штаны
        "canvas_pants", "sheath_pants", "padded_pants", "track_pants",
        "stash_pants", "bouncer_pants", "assault_fighter_pants",
        # обувь
        "sneakers", "army_boots", "runners",
    }
)


# Снятое с прилавка помечается здесь, одним проходом: иначе про `retired=True`
# пришлось бы помнить у каждой из тридцати семи вещей, а список выше — и так
# полный ответ на вопрос «чего в лавке больше нет».
ITEMS: tuple[Item, ...] = tuple(
    replace(item, retired=True) if item.code in RETIRED_GEAR else item
    for item in (
    # ---------- с чего начинают: уровни 1–3 ----------
    Item(
        "wraps",
        "Бинты",
        Slot.GLOVES,
        "🩹",
        strength=1,
        image=f"{ITEM_ART}/Hand_wraps_game_inventory_icon_202608281513.jpeg",
        accuracy=0.02,
        counter=0.03,
        requires=Stats(strength=4),
        price=40,
        for_classes=(WARRIOR, TANK),
    ),
    Item(
        "bandana",
        "Бандана",
        Slot.HEAD,
        "🧢",
        intuition=1,
        image=f"{ITEM_ART}/bandana.jpeg_202608281514.jpeg",
        armor_min=0,
        armor_max=1,
        anticrit=0.02,
        requires=Stats(intuition=4),
        price=45,
        for_classes=(ASSASSIN,),
    ),
    Item(
        "canvas_pants",
        "Брезентовые штаны",
        Slot.PANTS,
        "👖",
        hp=6,
        image=f"{ITEM_ART}/Folded_work_trousers_game_icon_202608281512.jpeg",
        armor_min=0,
        armor_max=1,
        level_required=2,
        requires=Stats(endurance=5),
        price=45,
        for_classes=(TANK,),
    ),
    Item(
        "wide_belt",
        "Широкий пояс",
        Slot.BELT,
        "🥋",
        hp=6,
        image=f"{ITEM_ART}/Leather_belt_game_icon_202608281513.jpeg",
        armor_min=0,
        armor_max=1,
        level_required=2,
        requires=Stats(endurance=5),
        price=50,
        for_classes=(TANK, WARRIOR),
    ),
    Item(
        "sneakers",
        "Кеды",
        Slot.BOOTS,
        "👟",
        agility=1,
        armor_min=0,
        armor_max=1,
        dodge=0.05,
        level_required=2,
        requires=Stats(agility=5),
        price=45,
        for_classes=(ROGUE,),
    ),
    Item(
        "knuckles",
        "Кастет",
        Slot.WEAPON,
        "🔩",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Brass_knuckle_game_inventory_icon_202608280127.jpeg",
        instrumental="кастетом",
        strength=1,
        damage_min=2,
        damage_max=4,
        accuracy=0.05,
        level_required=3,
        requires=Stats(strength=6),
        price=80,
        for_classes=(WARRIOR,),
    ),
    Item(
        "leather_jacket",
        "Косуха",
        Slot.JACKET,
        "🧥",
        hp=11,
        image=f"{ITEM_ART}/Battered_leather_biker_jacket_icon_202608281513.jpeg",
        armor_min=1,
        armor_max=3,
        level_required=3,
        requires=Stats(endurance=6),
        price=90,
        for_classes=(TANK, WARRIOR),
    ),
    # Футболки — базовый слой под верхней одеждой. Броня у них меньше, чем
    # у куртки того же уровня: они прикрывают те же корпус и живот, и их
    # брони складываются. Первые две без требований намеренно — слот новый,
    # и на первых уровнях в него должно быть что надеть.
    # Единственная вещь прежней лавки, которую пак не обошёл, а переписал:
    # футболка «всем» в нём одна, и это она. Цена и запас — из пака,
    # картинка и код прежние, поэтому у тех, кто уже носит майку, она просто
    # стала лучше
    Item(
        "wife_beater",
        "Майка-алкоголичка",
        Slot.SHIRT,
        "🎽",
        hp=30,
        image=art.shirt("wife_beater"),
        price=50,
    ),
    Item(
        "club_tee",
        "Клубная футболка",
        Slot.SHIRT,
        "👕",
        hp=5,
        image=art.shirt("club_tee"),
        level_required=2,
        price=50,
    ),
    # Набор ассасина: четыре усиленные вещи под ручные тесты боя, как и
    # первая четвёрка. Занимают слоты, которых у той четвёрки нет, — вместе
    # они собираются в полный комплект.
    Item(
        "throwing_belt",
        "Пояс с метательными",
        Slot.BELT,
        "🥷",
        intuition=1,
        armor_min=0,
        armor_max=1,
        crit=0.05,
        counter=0.05,
        level_required=5,
        price=50,
        for_classes=(ASSASSIN,),
    ),
    Item(
        "shadow_coat",
        "Плащ душителя",
        Slot.JACKET,
        "🧥",
        agility=1,
        intuition=1,
        armor_min=1,
        armor_max=2,
        dodge=0.05,
        crit=0.05,
        level_required=5,
        price=95,
        for_classes=(ASSASSIN,),
    ),
    Item(
        "sheath_pants",
        "Штаны с ножнами",
        Slot.PANTS,
        "👖",
        agility=1,
        armor_min=1,
        armor_max=2,
        dodge=0.05,
        accuracy=0.05,
        level_required=5,
        price=50,
        for_classes=(ASSASSIN,),
    ),
    Item(
        "bar_lid",
        "Крышка от бочки",
        Slot.OFFHAND,
        "🛢",
        kind=ItemKind.SHIELD,
        image=f"{ADDED_ART}/Game_inventory_shield_icon_202608280250.jpeg",
        hp=6,
        armor_min=2,
        armor_max=4,
        anticrit=0.03,
        level_required=3,
        requires=Stats(strength=6, endurance=5),
        price=70,
        for_classes=(TANK,),
    ),
    # ---------- 4 уровень: первое настоящее оружие ----------
    Item(
        "pipe",
        "Деревянная бита",
        Slot.WEAPON,
        "🪵",
        image=f"{WEAPON_ART}/Customized_wooden_baseball_bat_icon_202608280128.jpeg",
        kind=ItemKind.WEAPON,
        instrumental="деревянной битой",
        strength=1,
        damage_min=4,
        damage_max=7,
        accuracy=0.08,
        anticrit=0.04,
        level_required=4,
        requires=Stats(strength=12),
        price=150,
        for_classes=(WARRIOR,),
    ),
    Item(
        "switchblade",
        "Выкидуха",
        Slot.WEAPON,
        "🔪",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Folding_knife_game_inventory_icon_202608280132.jpeg",
        instrumental="выкидухой",
        agility=1,
        damage_min=4,
        damage_max=7,
        dodge=0.04,
        anticrit=0.02,
        level_required=4,
        requires=Stats(agility=12),
        price=150,
        for_classes=(ROGUE,),
    ),
    Item(
        "awl",
        "Строительный нож",
        Slot.WEAPON,
        "🔪",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Utility_knife_game_inventory_icon_202608280152.jpeg",
        instrumental="строительным ножом",
        intuition=1,
        damage_min=2,
        damage_max=9,
        crit=0.04,
        accuracy=0.08,
        level_required=4,
        requires=Stats(intuition=12),
        price=150,
        for_classes=(ASSASSIN,),
    ),
    Item(
        "crowbar",
        "Монтировка",
        Slot.WEAPON,
        "🔧",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Game_inventory_crowbar_icon_202608280137.jpeg",
        instrumental="монтировкой",
        damage_min=5,
        damage_max=6,
        accuracy=0.08,
        anticrit=0.08,
        level_required=4,
        requires=Stats(endurance=12),
        price=150,
        for_classes=(TANK,),
    ),
    Item(
        "knife",
        "Нож",
        Slot.WEAPON,
        "🔪",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Open_folding_knife_game_icon_202608280130.jpeg",
        instrumental="ножом",
        damage_min=4,
        damage_max=7,
        level_required=4,
        price=110,
        # Ни процентов, ни требований: первое, что берут, когда не накопил
        # на своё. Дешевле классового оружия ровно потому, что голое.
    ),
    Item(
        "skull_tee",
        "Футболка с черепом",
        Slot.SHIRT,
        "💀",
        hp=6,
        image=art.shirt("skull_tee"),
        level_required=4,
        requires=Stats(strength=12),
        price=70,
        for_classes=(WARRIOR, TANK),
    ),
    # ---------- 5 уровень: куртки, штаны, наручи, пояса ----------
    Item(
        "biker_jacket",
        "Клёпаная косуха",
        Slot.JACKET,
        "🧥",
        hp=16,
        image=f"{ITEM_ART}/Leather_biker_jacket_game_icon_202608281513.jpeg",
        armor_min=3,
        armor_max=5,
        anticrit=0.03,
        level_required=5,
        requires=Stats(endurance=13),
        price=100,
        for_classes=(TANK, WARRIOR),
    ),
    Item(
        "denim_vest",
        "Джинсовка без рукавов",
        Slot.JACKET,
        "🦺",
        agility=1,
        image=f"{ITEM_ART}/Denim_vest_game_inventory_icon_202608281513.jpeg",
        hp=8,
        armor_min=2,
        armor_max=3,
        dodge=0.03,
        level_required=5,
        requires=Stats(agility=13),
        price=100,
        for_classes=(ROGUE, ASSASSIN),
    ),
    Item(
        "padded_pants",
        "Брезент с накладками",
        Slot.PANTS,
        "👖",
        hp=6,
        image=f"{ITEM_ART}/Canvas_trousers_game_inventory_icon_202608281512.jpeg",
        armor_min=2,
        armor_max=4,
        level_required=5,
        requires=Stats(endurance=13),
        price=80,
        for_classes=(TANK, WARRIOR),
    ),
    Item(
        "track_pants",
        "Спортивки",
        Slot.PANTS,
        "🩳",
        agility=1,
        image=f"{ITEM_ART}/Tracksuit_bottoms_game_icon_202608281512.jpeg",
        hp=4,
        armor_min=1,
        armor_max=2,
        dodge=0.03,
        level_required=5,
        requires=Stats(agility=13),
        price=80,
        for_classes=(ROGUE,),
    ),
    Item(
        "leather_bracers",
        "Кожаные наручи",
        Slot.GLOVES,
        "🦾",
        strength=1,
        image=f"{ITEM_ART}/Leather_forearm_bracers_icon_202608281513.jpeg",
        accuracy=0.04,
        level_required=5,
        requires=Stats(strength=13),
        price=80,
        for_classes=(WARRIOR, TANK),
    ),
    Item(
        "dealer_bracers",
        "Наручи шулера",
        Slot.GLOVES,
        "🃏",
        intuition=1,
        image=f"{ITEM_ART}/Leather_dealer_cuffs_icon_202608281515.jpeg",
        hp=4,
        anticrit=0.04,
        level_required=5,
        requires=Stats(intuition=13),
        price=80,
        for_classes=(ASSASSIN,),
    ),
    Item(
        "buckle_belt",
        "Ремень с бляхой",
        Slot.BELT,
        "🥋",
        strength=1,
        image=f"{ITEM_ART}/Leather_belt_game_inventory_icon_202608281513.jpeg",
        armor_min=2,
        armor_max=3,
        level_required=5,
        requires=Stats(strength=13),
        price=80,
        for_classes=(WARRIOR, TANK),
    ),
    Item(
        "sheath_belt",
        "Пояс с ножнами",
        Slot.BELT,
        "🗡",
        intuition=1,
        image=f"{ITEM_ART}/Leather_belt_game_inventory_icon_202608281513%20(1).jpeg",
        armor_min=1,
        armor_max=2,
        crit=0.03,
        level_required=5,
        requires=Stats(intuition=13),
        price=80,
        for_classes=(ASSASSIN, ROGUE),
    ),
    Item(
        "buckler",
        "Щиток",
        Slot.OFFHAND,
        "🛡",
        kind=ItemKind.SHIELD,
        image=f"{ADDED_ART}/Game_inventory_steel_buckler_icon_202608280250.jpeg",
        agility=1,
        hp=6,
        armor_min=4,
        armor_max=7,
        dodge=0.03,
        level_required=5,
        requires=Stats(agility=13),
        price=110,
        for_classes=(ROGUE, WARRIOR, TANK),
    ),
    # ---------- 6 уровень: оружие, головные уборы, обувь ----------
    Item(
        "bat",
        "Бита",
        Slot.WEAPON,
        "🏏",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Bat_game_inventory_icon_202608280129.jpeg",
        instrumental="битой",
        strength=2,
        damage_min=7,
        damage_max=11,
        accuracy=0.22,
        anticrit=0.18,
        level_required=6,
        requires=Stats(strength=16),
        price=180,
        for_classes=(WARRIOR,),
    ),
    Item(
        "machete",
        "Гладиус",
        Slot.WEAPON,
        "🗡",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Roman_gladius_game_icon_202608280153.jpeg",
        instrumental="гладиусом",
        agility=2,
        damage_min=7,
        damage_max=11,
        dodge=0.18,
        anticrit=0.09,
        level_required=6,
        requires=Stats(agility=16),
        price=180,
        for_classes=(ROGUE,),
    ),
    Item(
        "stiletto",
        "Стилет",
        Slot.WEAPON,
        "🪡",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Stiletto_game_inventory_icon_202608280134.jpeg",
        instrumental="стилетом",
        intuition=2,
        damage_min=4,
        damage_max=14,
        crit=0.18,
        accuracy=0.22,
        level_required=6,
        requires=Stats(intuition=16),
        price=180,
        for_classes=(ASSASSIN,),
    ),
    Item(
        "sledge",
        "Кувалда",
        Slot.WEAPON,
        "🔨",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Sledgehammer_game_inventory_icon_202608280138.jpeg",
        instrumental="кувалдой",
        damage_min=8,
        damage_max=10,
        accuracy=0.22,
        anticrit=0.22,
        level_required=6,
        requires=Stats(endurance=16),
        price=180,
        for_classes=(TANK,),
    ),
    Item(
        "moto_helmet",
        "Мотошлем",
        Slot.HEAD,
        "🪖",
        hp=14,
        image=f"{ITEM_ART}/Scuffed_motorcycle_helmet_game_icon_202608281513.jpeg",
        armor_min=3,
        armor_max=5,
        anticrit=0.05,
        level_required=6,
        requires=Stats(endurance=15),
        price=100,
        for_classes=(TANK, WARRIOR),
    ),
    Item(
        "visor_cap",
        "Кепка с козырьком",
        Slot.HEAD,
        "🧢",
        intuition=2,
        image=f"{ITEM_ART}/Cap_game_inventory_icon_202608281513.jpeg",
        hp=4,
        armor_min=1,
        armor_max=2,
        crit=0.04,
        level_required=6,
        requires=Stats(intuition=15),
        price=100,
        for_classes=(ASSASSIN, ROGUE),
    ),
    Item(
        "army_boots",
        "Берцы",
        Slot.BOOTS,
        "🥾",
        hp=6,
        image=f"{ITEM_ART}/Combat_boots_game_inventory_icon_202608281512.jpeg",
        armor_min=2,
        armor_max=4,
        level_required=6,
        requires=Stats(endurance=15),
        price=100,
        for_classes=(WARRIOR, TANK),
    ),
    Item(
        "runners",
        "Беговые кроссовки",
        Slot.BOOTS,
        "👟",
        agility=2,
        image=f"{ITEM_ART}/Worn_trainers_game_inventory_icon_202608281511.jpeg",
        hp=4,
        armor_min=1,
        armor_max=2,
        dodge=0.04,
        level_required=6,
        requires=Stats(agility=15),
        price=100,
        for_classes=(ROGUE, ASSASSIN),
    ),
    Item(
        "rashguard",
        "Компрессионная футболка",
        Slot.SHIRT,
        "🥋",
        agility=1,
        image=art.shirt("rashguard"),
        dodge=0.04,
        level_required=6,
        requires=Stats(agility=15),
        price=100,
        for_classes=(ROGUE, ASSASSIN),
    ),
    # ---------- 7 уровень: оружие, перчатки, щиты ----------
    Item(
        "fire_axe",
        "Уличный топор",
        Slot.WEAPON,
        "🪓",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Customized_street_axe_game_icon_202608280139.jpeg",
        instrumental="топором",
        strength=2,
        damage_min=9,
        damage_max=16,
        accuracy=0.29,
        anticrit=0.25,
        level_required=7,
        requires=Stats(strength=18),
        price=240,
        for_classes=(WARRIOR,),
    ),
    Item(
        "balisong",
        "Балисонг",
        Slot.WEAPON,
        "🦋",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Butterfly_knife_game_inventory_icon_202608280133.jpeg",
        instrumental="балисонгом",
        agility=2,
        damage_min=9,
        damage_max=16,
        dodge=0.25,
        anticrit=0.12,
        level_required=7,
        requires=Stats(agility=18),
        price=240,
        for_classes=(ROGUE,),
    ),
    Item(
        "ice_pick",
        "Керамбит",
        Slot.WEAPON,
        "🪝",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Karambit_knife_game_icon_202608280141.jpeg",
        instrumental="керамбитом",
        intuition=2,
        damage_min=5,
        damage_max=20,
        crit=0.25,
        accuracy=0.29,
        level_required=7,
        requires=Stats(intuition=18),
        price=240,
        for_classes=(ASSASSIN,),
    ),
    Item(
        "chain",
        "Цепь с замком",
        Slot.WEAPON,
        "⛓",
        kind=ItemKind.WEAPON,
        image=f"{ADDED_ART}/Bicycle_chain_and_padlock_icon_202608280249.jpeg",
        instrumental="цепью",
        damage_min=11,
        damage_max=14,
        accuracy=0.29,
        anticrit=0.29,
        level_required=7,
        requires=Stats(endurance=18),
        price=240,
        for_classes=(TANK,),
    ),
    Item(
        "battered_gloves",
        "Битые перчатки",
        Slot.GLOVES,
        "🥊",
        strength=2,
        image=f"{ITEM_ART}/Leather_fighting_gloves_game_icon_202608281512.jpeg",
        accuracy=0.06,
        level_required=7,
        requires=Stats(strength=17),
        price=130,
        for_classes=(WARRIOR, TANK),
    ),
    Item(
        "fingerless_gloves",
        "Перчатки без пальцев",
        Slot.GLOVES,
        "🧤",
        agility=2,
        image=f"{ITEM_ART}/Fingerless_gloves_game_icon_202608281512.jpeg",
        hp=4,
        dodge=0.05,
        level_required=7,
        requires=Stats(agility=17),
        price=130,
        for_classes=(ROGUE,),
    ),
    Item(
        "card_gloves",
        "Перчатки крупье",
        Slot.GLOVES,
        "🎴",
        intuition=2,
        image=f"{ITEM_ART}/Croupier_gloves_game_inventory_icon_202608281512.jpeg",
        hp=4,
        crit=0.05,
        level_required=7,
        requires=Stats(intuition=17),
        price=130,
        for_classes=(ASSASSIN,),
    ),
    Item(
        "road_sign",
        "Дорожный знак",
        Slot.OFFHAND,
        "🚧",
        kind=ItemKind.SHIELD,
        image=f"{ADDED_ART}/Shield_made_from_road_sign_202608280250.jpeg",
        hp=22,
        armor_min=7,
        armor_max=11,
        anticrit=0.06,
        level_required=7,
        requires=Stats(strength=15, endurance=17),
        price=160,
        for_classes=(TANK,),
    ),
    # ---------- 8 уровень: последнее оружие ----------
    Item(
        "cleaver",
        "Тесак",
        Slot.WEAPON,
        "⚔",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Butcher_cleaver_game_icon_202608280140.jpeg",
        instrumental="тесаком",
        strength=3,
        damage_min=13,
        damage_max=21,
        accuracy=0.36,
        anticrit=0.32,
        level_required=8,
        requires=Stats(strength=20),
        price=300,
        for_classes=(WARRIOR,),
    ),
    Item(
        "razor",
        "Парные ножи",
        Slot.WEAPON,
        "✂️",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Crossed_street_knives_game_icon_202608280148.jpeg",
        instrumental="парными ножами",
        agility=3,
        damage_min=13,
        damage_max=21,
        dodge=0.32,
        anticrit=0.16,
        level_required=8,
        requires=Stats(agility=20),
        price=300,
        for_classes=(ROGUE,),
    ),
    Item(
        "needle",
        "Тактический нож",
        Slot.WEAPON,
        "🔪",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Tactical_knife_game_inventory_icon_202608280151.jpeg",
        instrumental="тактическим ножом",
        intuition=3,
        damage_min=7,
        damage_max=27,
        crit=0.32,
        accuracy=0.36,
        level_required=8,
        requires=Stats(intuition=20),
        price=300,
        for_classes=(ASSASSIN,),
    ),
    Item(
        "pry_bar",
        "Лом",
        Slot.WEAPON,
        "🦯",
        kind=ItemKind.WEAPON,
        image=f"{ADDED_ART}/Forged_steel_pry_bar_icon_202608280249.jpeg",
        instrumental="ломом",
        damage_min=15,
        damage_max=19,
        accuracy=0.36,
        anticrit=0.36,
        level_required=8,
        requires=Stats(endurance=20),
        price=300,
        for_classes=(TANK,),
    ),
    Item(
        "katana",
        "Катана",
        Slot.WEAPON,
        "🗡",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Katana_game_inventory_icon_202608280154.jpeg",
        instrumental="катаной",
        strength=2,
        damage_min=12,
        damage_max=22,
        level_required=8,
        requires=Stats(strength=18),
        price=260,
        for_classes=(WARRIOR, ROGUE),
    ),
    Item(
        "greatsword",
        "Двуручный меч",
        Slot.WEAPON,
        "⚔️",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Two-handed_sword_game_icon_202608280159.jpeg",
        instrumental="двуручным мечом",
        strength=3,
        damage_min=15,
        damage_max=19,
        level_required=8,
        requires=Stats(strength=20),
        price=270,
        for_classes=(WARRIOR, TANK),
    ),
    Item(
        "kevlar_tee",
        "Кевларовая футболка",
        Slot.SHIRT,
        "🦺",
        hp=8,
        image=art.shirt("kevlar_tee"),
        level_required=8,
        anticrit=0.05,
        requires=Stats(endurance=20),
        price=140,
        for_classes=(TANK, WARRIOR),
    ),
    Item(
        "riot_shield",
        "Штурмовой щит",
        Slot.OFFHAND,
        "🛡",
        kind=ItemKind.SHIELD,
        hp=20,
        armor_min=10,
        armor_max=15,
        anticrit=0.08,
        level_required=8,
        requires=Stats(strength=18, endurance=20),
        price=220,
        for_classes=(TANK, WARRIOR),
    ),
    # ---------- 9 уровень: чем добивают на потолке ----------
    # До этой ступени доходят единицы, поэтому цена кусается, а требования
    # рассчитаны на развитый билд своего класса, а не на универсала.
    Item(
        "viking_axe",
        "Секира викинга",
        Slot.WEAPON,
        "🪓",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Viking_battle_axe_game_icon_202608280222.jpeg",
        instrumental="секирой",
        strength=4,
        damage_min=17,
        damage_max=25,
        accuracy=0.43,
        anticrit=0.39,
        level_required=9,
        requires=Stats(strength=22),
        price=400,
        for_classes=(WARRIOR,),
    ),
    Item(
        "nail_bat",
        "Бита с гвоздями",
        Slot.WEAPON,
        "🏏",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Game_inventory_icon_of_bat_202608280221.jpeg",
        instrumental="битой",
        strength=2,
        agility=2,
        damage_min=16,
        damage_max=26,
        dodge=0.39,
        anticrit=0.2,
        level_required=9,
        requires=Stats(agility=22),
        price=400,
        for_classes=(ROGUE,),
    ),
    Item(
        "shiv",
        "Заточка",
        Slot.WEAPON,
        "📌",
        kind=ItemKind.WEAPON,
        image=f"{ADDED_ART}/Shiv_game_inventory_icon_202608280250.jpeg",
        instrumental="заточкой",
        intuition=4,
        damage_min=9,
        damage_max=33,
        crit=0.39,
        accuracy=0.43,
        level_required=9,
        requires=Stats(intuition=22),
        price=400,
        for_classes=(ASSASSIN,),
    ),
    Item(
        "splitting_axe",
        "Колун",
        Slot.WEAPON,
        "🪵",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Splitting_axe_game_inventory_icon_202608280223.jpeg",
        instrumental="колуном",
        strength=3,
        damage_min=19,
        damage_max=23,
        accuracy=0.43,
        anticrit=0.43,
        level_required=9,
        requires=Stats(endurance=24),
        price=400,
        for_classes=(TANK,),
    ),
    # ---------- награды: их не покупают, их выдают ----------
    # Стилету не нашлось ступени на прилавке: на пятом уровне оружия нет
    # вовсе, а на четвёртом и шестом у ассасина уже есть своё — шило и
    # стилет. Дать ему числа между ступенями значит выдать ассасину целый
    # тир форы над всеми, кто в это время ходит с оружием своего уровня
    # (круг классов на пятом уровне на этом и ломался). Поэтому он не
    # товар, а награда: приходит вместе с подпиской, как и клинок.
    Item(
        "assassin_stiletto",
        "Стилет ассасина",
        Slot.WEAPON,
        "🗡️",
        kind=ItemKind.WEAPON,
        instrumental="стилетом",
        intuition=1,
        damage_min=3,
        damage_max=11,
        crit=0.11,
        accuracy=0.15,
        level_required=5,
        reward=True,
        for_classes=(ASSASSIN,),
    ),
    # Кувалда Босса Казино. Не товар и не награда игроку: её носит один
    # боец на весь клуб, и купить её нельзя. Числа нарочно не похожи на
    # прилавочные — медленная и сокрушительная: замах широкий, точность
    # низкая. Обычная кувалда с прилавка бьёт на 8–10 и ровно, а эта
    # редко доходит и почти сносит, когда доходит. Босс, одетый по
    # прилавку, проигрывал одетому игроку — теперь у него есть своё
    Item(
        "boss_sledge",
        "Кувалда Босса",
        Slot.WEAPON,
        "🔨",
        kind=ItemKind.WEAPON,
        instrumental="кувалдой",
        strength=3,
        # Средний урон — ровно десятой ступени (у биты 22–28, тут 10–40), а
        # «медленная и сокрушительная» живёт в разбросе, а не в слабой
        # строке. Точность и антикрит взяты по лестнице: она у танкового
        # оружия ровная, по 0.07 за ступень, и выбиваться из неё нечему
        damage_min=10,
        damage_max=40,
        accuracy=0.50,
        anticrit=0.50,
        level_required=10,
        requires=Stats(endurance=26),
        reward=True,
        for_classes=(TANK,),
    ),
    # Остальной комплект Босса. Числа скопированы с прилавочных вещей,
    # которые он носил раньше: менялась не сила, а вид. Свои коды нужны
    # ради картинок — общий код означал бы общую картинку, и новый арт
    # перекрасил бы мотошлем половине клуба
    Item(
        "boss_helmet",
        "Шлем Босса",
        Slot.HEAD,
        "🪖",
        strength=2,
        hp=30,
        armor_min=8,
        armor_max=10,
        anticrit=0.2,
        level_required=10,
        requires=Stats(endurance=15),
        reward=True,
        for_classes=(TANK,),
    ),
    Item(
        "boss_shield",
        "Щит Босса",
        Slot.OFFHAND,
        "🛡",
        kind=ItemKind.SHIELD,
        hp=20,
        armor_min=10,
        armor_max=15,
        anticrit=0.08,
        level_required=10,
        requires=Stats(strength=18, endurance=20),
        reward=True,
        for_classes=(TANK,),
    ),
    Item(
        "boss_tee",
        "Поддоспешник Босса",
        Slot.SHIRT,
        "👕",
        strength=2,
        agility=2,
        intuition=2,
        hp=60,
        level_required=10,
        requires=Stats(endurance=20),
        reward=True,
        for_classes=(TANK,),
    ),
    Item(
        "boss_belt",
        "Пояс Босса",
        Slot.BELT,
        "🔗",
        strength=2,
        agility=1,
        intuition=1,
        hp=25,
        armor_min=10,
        armor_max=12,
        anticrit=0.3,
        level_required=10,
        requires=Stats(strength=14),
        reward=True,
        for_classes=(TANK,),
    ),
    Item(
        "boss_gloves",
        "Перчатки Босса",
        Slot.GLOVES,
        "🧤",
        strength=1,
        hp=15,
        anticrit=0.15,
        level_required=10,
        requires=Stats(strength=17),
        reward=True,
        for_classes=(TANK,),
    ),
    Item(
        "boss_jacket",
        "Бронекуртка Босса",
        Slot.JACKET,
        "🧥",
        strength=2,
        hp=60,
        armor_min=8,
        armor_max=10,
        anticrit=0.2,
        level_required=10,
        requires=Stats(endurance=15),
        reward=True,
        for_classes=(TANK,),
    ),
    Item(
        "boss_pants",
        "Штаны Босса",
        Slot.PANTS,
        "👖",
        strength=2,
        agility=2,
        intuition=2,
        hp=40,
        armor_min=10,
        armor_max=12,
        anticrit=0.3,
        level_required=10,
        requires=Stats(endurance=14),
        reward=True,
        for_classes=(TANK,),
    ),
    Item(
        "boss_boots",
        "Берцы Босса",
        Slot.BOOTS,
        "🥾",
        strength=1,
        hp=20,
        armor_min=7,
        armor_max=9,
        anticrit=0.15,
        level_required=10,
        requires=Stats(endurance=15),
        reward=True,
        for_classes=(TANK,),
    ),
    # Украшения Босса Казино: перстень и цепь. Числа — шестая ступень
    # ювелирной лестницы, как просил владелец: на кольце доля и запас
    # здоровья, на цепи то же плюс сила. Брони на них нет — у ювелира её
    # на этой ступени тоже нет, а броня украшений идёт на все зоны сразу
    # и на шестой ступени перевесила бы весь его доспех.
    #
    # Колец у босса три, и перстень у него один: `boss_kit` кладёт его во
    # все три клетки — так одеты все NPC клуба.
    Item(
        "boss_ring",
        "Перстень Босса",
        Slot.RING_RIGHT,
        hp=20,
        anticrit=0.15,
        level_required=10,
        requires=Stats(endurance=15),
        reward=True,
        for_classes=(TANK,),
    ),
    Item(
        "boss_necklace",
        "Цепь Босса",
        Slot.NECKLACE,
        strength=2,
        hp=25,
        anticrit=0.2,
        level_required=10,
        requires=Stats(endurance=15),
        reward=True,
        for_classes=(TANK,),
    ),
    Item(
        "hidden_blade",
        "Клинок ассасина",
        Slot.WEAPON,
        "🗡",
        kind=ItemKind.WEAPON,
        instrumental="скрытым клинком",
        image=f"{WEAPON_ART}/Concealed_blade_game_inventory_icon_202608291031.jpeg",
        intuition=2,
        damage_min=3,
        damage_max=9,
        crit=0.15,
        level_required=1,
        requires=Stats(intuition=7),
        reward=True,
        for_classes=(ASSASSIN,),
    ),
    # ---------- стенд: вещи с ручными числами ----------
    # Их числа нарочно выше потолка — на них руками проверяют, как эффекты
    # ведут себя в бою. Поэтому они награды: на прилавок не попадают, в
    # эталонный комплект не идут и в балансе не участвуют. Выдаются
    # адресно тестовым бойцам (bot.seed).
    Item(
        "test_wraps",
        "Бинты (стенд)",
        Slot.GLOVES,
        "🩹",
        strength=5,
        image=f"{ITEM_ART}/Hand_wraps_game_inventory_icon_202608281513.jpeg",
        accuracy=0.05,
        dodge=0.15,
        counter=0.15,
        requires=Stats(strength=4),
        reward=True,
        for_classes=(WARRIOR, TANK),
    ),
    Item(
        "test_bandana",
        "Бандана (стенд)",
        Slot.HEAD,
        "🧢",
        intuition=5,
        image=f"{ITEM_ART}/bandana.jpeg_202608281514.jpeg",
        armor_min=0,
        armor_max=1,
        crit=0.35,
        anticrit=0.25,
        requires=Stats(intuition=4),
        reward=True,
        for_classes=(ASSASSIN,),
    ),
    Item(
        "test_sneakers",
        "Кеды (стенд)",
        Slot.BOOTS,
        "👟",
        image=f"{ITEM_ART}/sneakers.jpeg",
        agility=5,
        armor_min=0,
        armor_max=1,
        dodge=0.15,
        crit=0.15,
        level_required=2,
        requires=Stats(agility=5),
        reward=True,
        for_classes=(ROGUE,),
    ),
    Item(
        "test_shirt",
        "Майка-алкоголичка (стенд)",
        Slot.SHIRT,
        "🎽",
        strength=3,
        agility=3,
        intuition=3,
        hp=60,
        image=art.shirt("wife_beater"),
        reward=True,
    ),
    # ---------- пятый уровень: шулер, вышибала и кулачный боец ----------
    #
    # Три набора на одну ступень: у трикстера трость и карманы, у танка
    # броня и кувалда, у воина дубинка и штурмовые брюки. Ассасин на этой
    # ступени донашивает своё: его клинок приходит с подпиской, и в
    # эталонный комплект (а значит, и в балансную матрицу) не попадает —
    # оттого на пятом уровне танк держит его увереннее обычного.
    #
    # Доли на оружии — по полосе своей ступени: нападение по низу, ответ
    # по верху. Трость шулера уворачивается и не подставляется под крит,
    # кувалда бьёт точно и терпит крит, дубинка точная и тоже терпит.
    Item(
        "cardsharp_cane",
        "Трость шулера",
        Slot.WEAPON,
        "🦯",
        kind=ItemKind.WEAPON,
        instrumental="тростью",
        agility=1,
        damage_min=4,
        damage_max=10,
        dodge=0.11,
        anticrit=0.06,
        level_required=5,
        requires=Stats(agility=13),
        price=170,
        for_classes=(ROGUE,),
    ),
    Item(
        "cardsharp_jacket",
        "Куртка шулера",
        Slot.JACKET,
        "🧥",
        agility=1,
        hp=8,
        armor_min=1,
        armor_max=3,
        dodge=0.05,
        level_required=5,
        requires=Stats(agility=13),
        price=130,
        for_classes=(ROGUE,),
    ),
    Item(
        "stash_pants",
        "Брюки с тайниками",
        Slot.PANTS,
        "👖",
        agility=1,
        hp=4,
        armor_min=1,
        armor_max=2,
        dodge=0.04,
        counter=0.04,
        level_required=5,
        requires=Stats(agility=12),
        price=120,
        for_classes=(ROGUE,),
    ),
    Item(
        "cardsharp_belt",
        "Пояс шулера",
        Slot.BELT,
        "🥋",
        intuition=1,
        armor_min=1,
        armor_max=2,
        crit=0.04,
        anticrit=0.03,
        level_required=5,
        requires=Stats(intuition=12),
        price=110,
        for_classes=(ROGUE,),
    ),
    Item(
        "bouncer_sledge",
        "Кувалда вышибалы",
        Slot.WEAPON,
        "🔨",
        kind=ItemKind.WEAPON,
        instrumental="кувалдой",
        damage_min=6,
        damage_max=8,
        accuracy=0.15,
        anticrit=0.15,
        level_required=5,
        requires=Stats(strength=13, endurance=14),
        price=170,
        for_classes=(TANK,),
    ),
    Item(
        "bouncer_armor_jacket",
        "Бронекуртка вышибалы",
        Slot.JACKET,
        "🧥",
        hp=18,
        armor_min=4,
        armor_max=6,
        anticrit=0.04,
        level_required=5,
        requires=Stats(endurance=15),
        price=140,
        for_classes=(TANK,),
    ),
    Item(
        "bouncer_pants",
        "Усиленные штаны вышибалы",
        Slot.PANTS,
        "👖",
        hp=10,
        armor_min=3,
        armor_max=5,
        level_required=5,
        requires=Stats(endurance=14),
        price=120,
        for_classes=(TANK,),
    ),
    Item(
        "power_belt",
        "Силовой пояс",
        Slot.BELT,
        "🥋",
        strength=2,
        hp=6,
        armor_min=2,
        armor_max=4,
        level_required=5,
        requires=Stats(strength=14),
        price=110,
        for_classes=(TANK, WARRIOR),
    ),
    Item(
        "pit_fighter_baton",
        "Дубинка бойца",
        Slot.WEAPON,
        "🏏",
        kind=ItemKind.WEAPON,
        instrumental="дубинкой",
        strength=1,
        damage_min=5,
        damage_max=9,
        accuracy=0.15,
        anticrit=0.11,
        level_required=5,
        requires=Stats(strength=14),
        price=170,
        for_classes=(WARRIOR,),
    ),
    Item(
        "pit_fighter_jacket",
        "Куртка бойца",
        Slot.JACKET,
        "🧥",
        strength=1,
        hp=14,
        armor_min=3,
        armor_max=5,
        accuracy=0.04,
        level_required=5,
        requires=Stats(strength=14),
        price=130,
        for_classes=(WARRIOR,),
    ),
    Item(
        "assault_fighter_pants",
        "Штурмовые брюки",
        Slot.PANTS,
        "👖",
        strength=1,
        hp=8,
        armor_min=2,
        armor_max=4,
        accuracy=0.03,
        level_required=5,
        requires=Stats(strength=13),
        price=120,
        for_classes=(WARRIOR,),
    ),
    Item(
        "knuckle_belt",
        "Пояс кулачника",
        Slot.BELT,
        "🥋",
        strength=1,
        hp=4,
        armor_min=2,
        armor_max=3,
        counter=0.05,
        level_required=5,
        requires=Stats(strength=13),
        price=110,
        for_classes=(WARRIOR,),
    ),
    # ---------- фанатский магазин «Северный Вал»: экипировка своей команды ----------
    #
    # Отдельный прилавок, а не следующая ступень клубной лавки. Вещи тут
    # десятого уровня и от тысячи кредитов — это десять уровней дохода за
    # одну вещь, поэтому в эталонный комплект они не идут: эталон — это
    # осмысленно одетый боец, а не тот, кто копил семь тысяч. Числа при
    # этом держатся в тех же границах, что и витрина клуба: +4 плоских,
    # 10% на одежде и полоса 45–50% на оружии десятого уровня.
    #
    # Линий три, по фанатским ролям: тяжёлая «босса», средняя «воина» и
    # лёгкая техничная. Лёгкую носят и ассасин, и трикстер, поэтому
    # надевается она по выносливости — ловкость с интуицией у этих двоих
    # разные, и общее требование отсекло бы одного из них.
    Item(
        "fan_boss_bat",
        "Бита с гвоздями",
        Slot.WEAPON,
        "🔨",
        kind=ItemKind.WEAPON,
        instrumental="битой с гвоздями",
        strength=3,
        damage_min=22,
        damage_max=28,
        accuracy=0.5,
        anticrit=0.5,
        level_required=10,
        requires=Stats(strength=15, endurance=26),
        price=1600,
        for_classes=(TANK,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_boss_shield",
        "Щит фанатского сектора",
        Slot.OFFHAND,
        "🛡",
        kind=ItemKind.SHIELD,
        hp=24,
        armor_min=12,
        armor_max=16,
        anticrit=0.09,
        level_required=10,
        requires=Stats(strength=15, endurance=24),
        price=1400,
        for_classes=(TANK, WARRIOR),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_boss_polo",
        "Плотное поло",
        Slot.SHIRT,
        "👕",
        strength=3,
        agility=3,
        intuition=3,
        hp=75,
        anticrit=0.06,
        level_required=10,
        requires=Stats(endurance=24),
        price=1000,
        for_classes=(TANK,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_boss_jacket",
        "Тяжёлая полевая куртка",
        Slot.JACKET,
        "🧥",
        strength=5,
        agility=3,
        intuition=3,
        hp=95,
        armor_min=15,
        armor_max=17,
        anticrit=0.55,
        level_required=10,
        requires=Stats(endurance=24),
        price=1500,
        for_classes=(TANK,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_boss_track_pants",
        "Плотные спортивные штаны",
        Slot.PANTS,
        "👖",
        strength=3,
        agility=3,
        intuition=3,
        hp=50,
        armor_min=13,
        armor_max=15,
        anticrit=0.45,
        level_required=10,
        requires=Stats(endurance=22),
        price=1100,
        for_classes=(TANK,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_boss_sneakers",
        "Замшевые террас-кроссовки",
        Slot.BOOTS,
        "👟",
        strength=5,
        hp=40,
        armor_min=14,
        armor_max=16,
        anticrit=0.55,
        level_required=10,
        requires=Stats(endurance=22),
        price=1100,
        for_classes=(TANK,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_boss_cap",
        "Кепка фанатского сектора",
        Slot.HEAD,
        "🧢",
        strength=5,
        hp=75,
        armor_min=14,
        armor_max=16,
        anticrit=0.55,
        level_required=10,
        requires=Stats(endurance=24),
        price=1200,
        for_classes=(TANK,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_boss_belt",
        "Широкий кожаный пояс",
        Slot.BELT,
        "🥋",
        strength=3,
        agility=2,
        intuition=2,
        hp=35,
        armor_min=13,
        armor_max=15,
        anticrit=0.45,
        level_required=10,
        requires=Stats(strength=14, endurance=20),
        price=1000,
        for_classes=(TANK,),
        shelf=FAN_SHELF,
    ),
# ---------- украшения фанатского прилавка ----------
#
# Девятая ступень ювелирной лестницы в фанатском виде: числа у них те
# же, что у украшений ювелира девятого уровня, — так решил владелец. И
# цена поэтому ювелирная, а не валовская: кольцо 200, кулон 500. Платят
# тут не за силу, а за вид — и ещё за то, что это падает с рейда: полка
# «Северного Вала» и есть добыча со стычки.
#
# Броня на кулонах прикрывает все зоны, как щит, а кольцо носится в три
# клетки — поэтому на гопнике кольцо складывается втрое. Это и есть
# главная прибавка банде за этот заход.
    Item(
        "fan_boss_ring",
        "Тяжёлая печатка",
        Slot.RING_RIGHT,
        hp=25,
        armor_min=5,
        armor_max=10,
        level_required=9,
        requires=Stats(strength=20, endurance=20),
        price=200,
        for_classes=(TANK,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_boss_necklace",
        "Толстая цепь",
        Slot.NECKLACE,
        strength=4,
        hp=30,
        armor_min=11,
        armor_max=13,
        accuracy=0.25,
        anticrit=0.4,
        level_required=9,
        requires=Stats(endurance=25),
        price=500,
        for_classes=(TANK,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_warrior_bat",
        "Бейсбольная бита",
        Slot.WEAPON,
        "🏏",
        kind=ItemKind.WEAPON,
        instrumental="бейсбольной битой",
        strength=4,
        damage_min=19,
        damage_max=31,
        accuracy=0.5,
        anticrit=0.46,
        level_required=10,
        requires=Stats(strength=24),
        price=1500,
        for_classes=(WARRIOR,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_warrior_tee",
        "Спортивная футболка",
        Slot.SHIRT,
        "🎽",
        strength=5,
        agility=3,
        intuition=3,
        hp=30,
        counter=0.03,
        level_required=10,
        requires=Stats(strength=20),
        price=1000,
        for_classes=(WARRIOR,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_warrior_harrington",
        "Куртка-харрингтон",
        Slot.JACKET,
        "🧥",
        strength=5,
        agility=3,
        intuition=3,
        hp=75,
        armor_min=14,
        armor_max=16,
        accuracy=0.35,
        dodge=0.3,
        crit=0.3,
        anticrit=0.3,
        level_required=10,
        requires=Stats(strength=22),
        price=1400,
        for_classes=(WARRIOR,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_warrior_track_pants",
        "Спортивные штаны",
        Slot.PANTS,
        "👖",
        strength=4,
        agility=2,
        intuition=2,
        hp=40,
        armor_min=12,
        armor_max=14,
        accuracy=0.3,
        dodge=0.25,
        crit=0.25,
        anticrit=0.15,
        level_required=10,
        requires=Stats(strength=20),
        price=1100,
        for_classes=(WARRIOR,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_warrior_sneakers",
        "Массивные ретро-кроссовки",
        Slot.BOOTS,
        "👟",
        strength=3,
        agility=2,
        intuition=2,
        hp=35,
        armor_min=13,
        armor_max=15,
        accuracy=0.35,
        dodge=0.3,
        crit=0.3,
        anticrit=0.3,
        counter=0.04,
        level_required=10,
        requires=Stats(strength=20),
        price=1100,
        for_classes=(WARRIOR,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_warrior_cap",
        "Ретро-спортивная кепка",
        Slot.HEAD,
        "🧢",
        strength=3,
        agility=2,
        intuition=2,
        hp=55,
        armor_min=13,
        armor_max=15,
        accuracy=0.35,
        dodge=0.3,
        crit=0.3,
        anticrit=0.3,
        level_required=10,
        requires=Stats(strength=20),
        price=1200,
        for_classes=(WARRIOR,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_warrior_belt",
        "Тканевый спортивный пояс",
        Slot.BELT,
        "🥋",
        strength=3,
        agility=2,
        intuition=2,
        hp=30,
        armor_min=12,
        armor_max=14,
        accuracy=0.3,
        dodge=0.25,
        crit=0.25,
        anticrit=0.15,
        level_required=10,
        requires=Stats(strength=20),
        price=1000,
        for_classes=(WARRIOR,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_warrior_ring",
        "Печатка с гербом",
        Slot.RING_RIGHT,
        strength=2,
        agility=2,
        intuition=2,
        hp=25,
        level_required=9,
        requires=Stats(strength=20, endurance=20),
        price=200,
        for_classes=(WARRIOR,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_warrior_necklace",
        "Цепь с гербом",
        Slot.NECKLACE,
        strength=2,
        agility=1,
        intuition=1,
        hp=25,
        armor_min=10,
        armor_max=12,
        accuracy=0.2,
        dodge=0.2,
        crit=0.2,
        anticrit=0.2,
        level_required=9,
        requires=Stats(strength=25, endurance=20),
        price=500,
        for_classes=(WARRIOR,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_assassin_knife",
        "Складной нож",
        Slot.WEAPON,
        "🔪",
        kind=ItemKind.WEAPON,
        instrumental="складным ножом",
        intuition=4,
        damage_min=11,
        damage_max=39,
        crit=0.46,
        accuracy=0.5,
        level_required=10,
        requires=Stats(intuition=20),
        price=1500,
        for_classes=(ASSASSIN,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_assassin_polo",
        "Модное поло",
        Slot.SHIRT,
        "👕",
        strength=3,
        agility=3,
        intuition=5,
        hp=30,
        dodge=0.04,
        level_required=10,
        requires=Stats(endurance=18),
        price=1000,
        for_classes=(ASSASSIN, ROGUE),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_assassin_track_jacket",
        "Лёгкая спортивная куртка",
        Slot.JACKET,
        "🧥",
        strength=3,
        agility=3,
        intuition=5,
        hp=50,
        armor_min=13,
        armor_max=15,
        accuracy=0.35,
        crit=0.55,
        dodge=0.04,
        level_required=10,
        requires=Stats(endurance=18),
        price=1400,
        for_classes=(ASSASSIN, ROGUE),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_assassin_track_pants",
        "Зауженные модные штаны",
        Slot.PANTS,
        "👖",
        strength=4,
        intuition=4,
        hp=30,
        armor_min=11,
        armor_max=13,
        accuracy=0.3,
        crit=0.45,
        dodge=0.04,
        level_required=10,
        requires=Stats(endurance=18),
        price=1100,
        for_classes=(ASSASSIN, ROGUE),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_assassin_sneakers",
        "Лёгкие беговые кроссовки",
        Slot.BOOTS,
        "👟",
        intuition=5,
        hp=20,
        armor_min=12,
        armor_max=14,
        crit=0.55,
        anticrit=0.35,
        dodge=0.05,
        level_required=10,
        requires=Stats(endurance=18),
        price=1100,
        for_classes=(ASSASSIN, ROGUE),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_assassin_cap",
        "Модная кепка",
        Slot.HEAD,
        "🧢",
        intuition=5,
        hp=30,
        armor_min=12,
        armor_max=14,
        accuracy=0.35,
        crit=0.55,
        level_required=10,
        requires=Stats(endurance=18),
        price=1200,
        for_classes=(ASSASSIN, ROGUE),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_assassin_belt",
        "Компактный тактический пояс",
        Slot.BELT,
        "🥋",
        strength=2,
        intuition=4,
        hp=25,
        armor_min=11,
        armor_max=13,
        accuracy=0.3,
        crit=0.45,
        counter=0.04,
        level_required=10,
        requires=Stats(endurance=18),
        price=1000,
        for_classes=(ASSASSIN, ROGUE),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_assassin_ring",
        "Чёрное кольцо",
        Slot.RING_RIGHT,
        dodge=0.3,
        crit=0.3,
        level_required=9,
        requires=Stats(agility=20, intuition=20),
        price=200,
        for_classes=(ASSASSIN,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_assassin_necklace",
        "Шнурок с клыком",
        Slot.NECKLACE,
        intuition=4,
        hp=10,
        armor_min=9,
        armor_max=11,
        crit=0.4,
        anticrit=0.25,
        level_required=9,
        requires=Stats(intuition=25),
        price=500,
        for_classes=(ASSASSIN,),
        shelf=FAN_SHELF,
    ),
    # Линия трикстера: та же лёгкая мода, но собранная под уворот. У
    # ассасина в этом магазине крит, у трикстера — уворот на каждой вещи:
    # оба носят лёгкое, а держат удар по-разному.
    Item(
        "fan_rogue_umbrella",
        "Боевой зонт",
        Slot.WEAPON,
        "☂️",
        kind=ItemKind.WEAPON,
        instrumental="боевым зонтом",
        agility=4,
        damage_min=17,
        damage_max=31,
        dodge=0.46,
        anticrit=0.23,
        level_required=10,
        requires=Stats(agility=24),
        price=1600,
        for_classes=(ROGUE,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_rogue_polo",
        "Вязаное поло",
        Slot.SHIRT,
        "👕",
        strength=3,
        agility=5,
        intuition=3,
        hp=30,
        dodge=0.05,
        level_required=10,
        requires=Stats(endurance=18),
        price=1100,
        for_classes=(ROGUE,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_rogue_jacket",
        "Лёгкая модная куртка",
        Slot.JACKET,
        "🧥",
        strength=3,
        agility=5,
        intuition=3,
        hp=50,
        armor_min=13,
        armor_max=15,
        dodge=0.55,
        counter=0.35,
        level_required=10,
        requires=Stats(endurance=18),
        price=1500,
        for_classes=(ROGUE,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_rogue_track_pants",
        "Спортивные штаны",
        Slot.PANTS,
        "👖",
        strength=4,
        agility=4,
        hp=30,
        armor_min=11,
        armor_max=13,
        dodge=0.45,
        anticrit=0.3,
        level_required=10,
        requires=Stats(endurance=18),
        price=1200,
        for_classes=(ROGUE,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_rogue_sneakers",
        "Ретро-кроссовки",
        Slot.BOOTS,
        "👟",
        agility=5,
        hp=20,
        armor_min=12,
        armor_max=14,
        accuracy=0.35,
        dodge=0.55,
        level_required=10,
        requires=Stats(endurance=18),
        price=1200,
        for_classes=(ROGUE,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_rogue_cap",
        "Кепка",
        Slot.HEAD,
        "🧢",
        agility=5,
        hp=30,
        armor_min=12,
        armor_max=14,
        dodge=0.55,
        counter=0.35,
        level_required=10,
        requires=Stats(endurance=18),
        price=1300,
        for_classes=(ROGUE,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_rogue_belt",
        "Модный пояс",
        Slot.BELT,
        "🥋",
        strength=2,
        agility=4,
        hp=25,
        armor_min=11,
        armor_max=13,
        dodge=0.45,
        anticrit=0.3,
        counter=0.04,
        level_required=10,
        requires=Stats(endurance=18),
        price=1100,
        for_classes=(ROGUE,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_rogue_ring",
        "Узкое кольцо",
        Slot.RING_RIGHT,
        dodge=0.3,
        crit=0.3,
        level_required=9,
        requires=Stats(agility=20, intuition=20),
        price=200,
        for_classes=(ROGUE,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_rogue_necklace",
        "Цепочка с подвеской",
        Slot.NECKLACE,
        agility=4,
        hp=10,
        armor_min=9,
        armor_max=11,
        accuracy=0.25,
        dodge=0.4,
        level_required=9,
        requires=Stats(agility=25),
        price=500,
        for_classes=(ROGUE,),
        shelf=FAN_SHELF,
    ),
    # Лёгкий щит трикстера: не доска лидера, а щиток под руку. Брони
    # вдвое меньше, зато он не мешает уворачиваться и сам в уворот
    # добавляет. Блок от него всё равно на три зоны — щит он и есть щит,
    # и этим ценен на гопнике, который иначе дрался с пустой рукой
    Item(
        "fan_rogue_shield",
        "Лёгкий щит",
        Slot.OFFHAND,
        "🛡",
        kind=ItemKind.SHIELD,
        hp=10,
        armor_min=8,
        armor_max=11,
        dodge=0.3,
        level_required=10,
        requires=Stats(agility=24),
        price=1300,
        for_classes=(ROGUE,),
        shelf=FAN_SHELF,
    ),
    # ---------- лавка мага: только за звёзды ----------
    Item(
        "lightsaber",
        "Световой меч",
        Slot.WEAPON,
        "🗡",
        kind=ItemKind.WEAPON,
        instrumental="световым мечом",
        # У мага картинка лежит в png: у клинка есть свечение по краям
        image=f"{MAGIC_ART}/lightsaber.png",
        intuition=5,
        damage_min=7,
        damage_max=15,
        dodge=0.35,
        counter=0.25,
        level_required=2,
        requires=Stats(strength=10),
        stars=250,
    ),
    *SET_PIECES,
    *JEWEL_PIECES,
    )
)

CATALOGUE: dict[str, Item] = {item.code: item for item in ITEMS}

# Витрина лавки клуба: по типам вещей в порядке слотов карточки, внутри — от
# простого к дорогому. Вещи из лавки мага сюда не попадают: за кредиты их не
# купить, и висеть на прилавке рядом с кастетом им незачем.
SHOWCASE: tuple[Item, ...] = tuple(
    sorted(
        (
            item
            for item in ITEMS
            if not item.is_magic and item.on_sale and not item.shelf
            and not item.retired
        ),
        key=lambda item: (ALL_SLOTS.index(item.slot), item.level_required, item.price),
    )
)

# Прилавок фанатского магазина: та же раскладка по слотам, но свой товар.
# В витрину клуба он не входит — и потому не тянет за собой ни лестницу
# цен, ни правило «никто не отстаёт больше чем на три уровня»
FAN_ITEMS: tuple[Item, ...] = tuple(
    sorted(
        (item for item in ITEMS if item.shelf == FAN_SHELF and item.on_sale),
        key=lambda item: (ALL_SLOTS.index(item.slot), item.level_required, item.price),
    )
)

# Прилавок ювелира: кольца и ожерелья, и ничего кроме них. Полок здесь
# ровно две — `shop_sections` разложит товар по клеткам сам
JEWEL_ITEMS: tuple[Item, ...] = tuple(
    sorted(
        (item for item in ITEMS if item.shelf == JEWEL_SHELF and item.on_sale),
        key=lambda item: (ALL_SLOTS.index(item.slot), item.level_required, item.price),
    )
)

# Прилавок мага: только за звёзды
MAGIC_ITEMS: tuple[Item, ...] = tuple(
    sorted(
        (item for item in ITEMS if item.is_magic and item.on_sale),
        key=lambda item: item.stars,
    )
)


# Тематические прилавки по именам: у каждого свой товар и своя лестница
SHELVES: dict[str, tuple[Item, ...]] = {
    FAN_SHELF: FAN_ITEMS,
    JEWEL_SHELF: JEWEL_ITEMS,
}


def shelf_of(shelf: str = "") -> tuple[Item, ...]:
    """Товар названного прилавка: пусто — клубная витрина."""
    return SHELVES.get(shelf, SHOWCASE)


def shop_sections(shelf: str = "") -> list[tuple[Slot, tuple[Item, ...]]]:
    """Товары, разложенные по типам — так магазин и показывает их."""
    goods = shelf_of(shelf)
    return [
        (slot, tuple(item for item in goods if item.slot is slot))
        for slot in ALL_SLOTS
    ]


def items_unlocked_at(level: int) -> tuple[Item, ...]:
    """Что открывается ровно на этом уровне."""
    return tuple(item for item in SHOWCASE if item.level_required == level)


def get_item(code: str) -> Item | None:
    return CATALOGUE.get(code)
