"""Что лежит в лавке клуба: сами вещи, по одной записи на предмет.

Здесь только содержимое — числа, названия и картинки. Правила, по которым
предмет работает в бою, живут в `bot.game.gear`, а всё остальное берёт и
то и другое из `bot.game.equipment`: добавляя вещь, править нужно только
этот файл.

Товар открывается уровнем: с 4-го идёт оружие, с 5-го — куртки, штаны,
наручи и пояса, с 6-го обновляется оружие и приходят головные уборы с
обувью, с 7-го — оружие, перчатки и щиты, с 8-го — последнее оружие.
В каждом наборе есть вещь под каждый класс, но кредитов на всё не хватит:
на уровень капает около сотни, а набор стоит втрое дороже — в этом и
развилка.

Границы, за которые содержимому выходить нельзя, держит
`tests/test_content.py`: потолок процентов, лестница урона и плоских
прибавок, выносливости на вещах нет. Новая вещь проходит этот тест —
значит, она не ломает баланс классов.

Картинка обычно не указывается: вещь получает адрес от своего кода —
`items/<code>.jpeg`. Строка `image=` осталась у старых файлов, чьи имена
под это правило не подходят.
"""

from __future__ import annotations

from bot.game import art
from bot.game.classes import Stats
from bot.game.gear import ALL_SLOTS, Item, ItemKind, Slot

# Папки картинок в R2: у старых файлов адрес задан явно
ART = art.BUCKET
WEAPON_ART = art.WEAPONS
ADDED_ART = art.ADDED
ITEM_ART = art.ITEMS
MAGIC_ART = art.MAGIC

WARRIOR, ROGUE, ASSASSIN, TANK = "warrior", "rogue", "assassin", "tank"

# Прилавок фанатского магазина на Северном Валу: свой товар, своя цена и
# своя лестница. Пустой `shelf` — товар клубной лавки
FAN_SHELF = "fan"

ITEMS: tuple[Item, ...] = (
    # ---------- с чего начинают: уровни 1–3 ----------
    Item(
        "wraps",
        "Бинты",
        Slot.GLOVES,
        "🩹",
        strength=1,
        image=f"{ITEM_ART}/Hand_wraps_game_inventory_icon_202608281513.jpeg",
        accuracy=0.02,
        counter=0.03,
        requires=Stats(strength=4),
        price=40,
        for_classes=(WARRIOR, TANK),
    ),
    Item(
        "bandana",
        "Бандана",
        Slot.HEAD,
        "🧢",
        intuition=1,
        image=f"{ITEM_ART}/bandana.jpeg_202608281514.jpeg",
        armor_min=0,
        armor_max=1,
        anticrit=0.02,
        requires=Stats(intuition=4),
        price=45,
        for_classes=(ASSASSIN,),
    ),
    Item(
        "canvas_pants",
        "Брезентовые штаны",
        Slot.PANTS,
        "👖",
        hp=6,
        image=f"{ITEM_ART}/Folded_work_trousers_game_icon_202608281512.jpeg",
        armor_min=0,
        armor_max=1,
        level_required=2,
        requires=Stats(endurance=5),
        price=45,
        for_classes=(TANK,),
    ),
    Item(
        "wide_belt",
        "Широкий пояс",
        Slot.BELT,
        "🥋",
        hp=6,
        image=f"{ITEM_ART}/Leather_belt_game_icon_202608281513.jpeg",
        armor_min=0,
        armor_max=1,
        level_required=2,
        requires=Stats(endurance=5),
        price=50,
        for_classes=(TANK, WARRIOR),
    ),
    Item(
        "sneakers",
        "Кеды",
        Slot.BOOTS,
        "👟",
        agility=1,
        armor_min=0,
        armor_max=1,
        dodge=0.05,
        level_required=2,
        requires=Stats(agility=5),
        price=45,
        for_classes=(ROGUE,),
    ),
    Item(
        "knuckles",
        "Кастет",
        Slot.WEAPON,
        "🔩",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Brass_knuckle_game_inventory_icon_202608280127.jpeg",
        instrumental="кастетом",
        strength=1,
        damage_min=2,
        damage_max=4,
        accuracy=0.02,
        level_required=3,
        requires=Stats(strength=6),
        price=80,
        for_classes=(WARRIOR,),
    ),
    Item(
        "leather_jacket",
        "Косуха",
        Slot.JACKET,
        "🧥",
        hp=11,
        image=f"{ITEM_ART}/Battered_leather_biker_jacket_icon_202608281513.jpeg",
        armor_min=1,
        armor_max=3,
        level_required=3,
        requires=Stats(endurance=6),
        price=90,
        for_classes=(TANK, WARRIOR),
    ),
    # Футболки — базовый слой под верхней одеждой. Броня у них меньше, чем
    # у куртки того же уровня: они прикрывают те же корпус и живот, и их
    # брони складываются. Первые две без требований намеренно — слот новый,
    # и на первых уровнях в него должно быть что надеть.
    Item(
        "wife_beater",
        "Майка-алкоголичка",
        Slot.SHIRT,
        "🎽",
        hp=4,
        image=art.shirt("wife_beater"),
        price=35,
    ),
    Item(
        "club_tee",
        "Клубная футболка",
        Slot.SHIRT,
        "👕",
        hp=5,
        image=art.shirt("club_tee"),
        level_required=2,
        price=50,
    ),
    # Набор ассасина: четыре усиленные вещи под ручные тесты боя, как и
    # первая четвёрка. Занимают слоты, которых у той четвёрки нет, — вместе
    # они собираются в полный комплект.
    Item(
        "throwing_belt",
        "Пояс с метательными",
        Slot.BELT,
        "🥷",
        intuition=1,
        armor_min=0,
        armor_max=1,
        crit=0.05,
        counter=0.05,
        level_required=5,
        price=50,
        for_classes=(ASSASSIN,),
    ),
    Item(
        "shadow_coat",
        "Плащ душителя",
        Slot.JACKET,
        "🧥",
        agility=1,
        intuition=1,
        armor_min=1,
        armor_max=2,
        dodge=0.05,
        crit=0.05,
        level_required=5,
        price=95,
        for_classes=(ASSASSIN,),
    ),
    Item(
        "sheath_pants",
        "Штаны с ножнами",
        Slot.PANTS,
        "👖",
        agility=1,
        armor_min=1,
        armor_max=2,
        dodge=0.05,
        accuracy=0.05,
        level_required=5,
        price=50,
        for_classes=(ASSASSIN,),
    ),
    Item(
        "bar_lid",
        "Крышка от бочки",
        Slot.OFFHAND,
        "🛢",
        kind=ItemKind.SHIELD,
        image=f"{ADDED_ART}/Game_inventory_shield_icon_202608280250.jpeg",
        hp=6,
        armor_min=2,
        armor_max=4,
        anticrit=0.03,
        level_required=3,
        requires=Stats(strength=6, endurance=5),
        price=70,
        for_classes=(TANK,),
    ),
    # ---------- 4 уровень: первое настоящее оружие ----------
    Item(
        "pipe",
        "Деревянная бита",
        Slot.WEAPON,
        "🪵",
        image=f"{WEAPON_ART}/Customized_wooden_baseball_bat_icon_202608280128.jpeg",
        kind=ItemKind.WEAPON,
        instrumental="деревянной битой",
        strength=1,
        damage_min=4,
        damage_max=7,
        accuracy=0.03,
        level_required=4,
        requires=Stats(strength=12),
        price=150,
        for_classes=(WARRIOR,),
    ),
    Item(
        "switchblade",
        "Выкидуха",
        Slot.WEAPON,
        "🔪",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Folding_knife_game_inventory_icon_202608280132.jpeg",
        instrumental="выкидухой",
        agility=1,
        damage_min=4,
        damage_max=7,
        dodge=0.03,
        level_required=4,
        requires=Stats(agility=12),
        price=150,
        for_classes=(ROGUE,),
    ),
    Item(
        "awl",
        "Строительный нож",
        Slot.WEAPON,
        "🔪",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Utility_knife_game_inventory_icon_202608280152.jpeg",
        instrumental="строительным ножом",
        intuition=1,
        damage_min=2,
        damage_max=9,
        crit=0.03,
        level_required=4,
        requires=Stats(intuition=12),
        price=150,
        for_classes=(ASSASSIN,),
    ),
    Item(
        "crowbar",
        "Монтировка",
        Slot.WEAPON,
        "🔧",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Game_inventory_crowbar_icon_202608280137.jpeg",
        instrumental="монтировкой",
        damage_min=5,
        damage_max=6,
        accuracy=0.03,
        anticrit=0.03,
        level_required=4,
        requires=Stats(endurance=12),
        price=150,
        for_classes=(TANK,),
    ),
    Item(
        "knife",
        "Нож",
        Slot.WEAPON,
        "🔪",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Open_folding_knife_game_icon_202608280130.jpeg",
        instrumental="ножом",
        damage_min=4,
        damage_max=7,
        level_required=4,
        price=110,
        # Ни процентов, ни требований: первое, что берут, когда не накопил
        # на своё. Дешевле классового оружия ровно потому, что голое.
    ),
    Item(
        "skull_tee",
        "Футболка с черепом",
        Slot.SHIRT,
        "💀",
        hp=6,
        image=art.shirt("skull_tee"),
        level_required=4,
        requires=Stats(strength=12),
        price=70,
        for_classes=(WARRIOR, TANK),
    ),
    # ---------- 5 уровень: куртки, штаны, наручи, пояса ----------
    Item(
        "biker_jacket",
        "Клёпаная косуха",
        Slot.JACKET,
        "🧥",
        hp=16,
        image=f"{ITEM_ART}/Leather_biker_jacket_game_icon_202608281513.jpeg",
        armor_min=3,
        armor_max=5,
        anticrit=0.03,
        level_required=5,
        requires=Stats(endurance=13),
        price=100,
        for_classes=(TANK, WARRIOR),
    ),
    Item(
        "denim_vest",
        "Джинсовка без рукавов",
        Slot.JACKET,
        "🦺",
        agility=1,
        image=f"{ITEM_ART}/Denim_vest_game_inventory_icon_202608281513.jpeg",
        hp=8,
        armor_min=2,
        armor_max=3,
        dodge=0.03,
        level_required=5,
        requires=Stats(agility=13),
        price=100,
        for_classes=(ROGUE, ASSASSIN),
    ),
    Item(
        "padded_pants",
        "Брезент с накладками",
        Slot.PANTS,
        "👖",
        hp=6,
        image=f"{ITEM_ART}/Canvas_trousers_game_inventory_icon_202608281512.jpeg",
        armor_min=2,
        armor_max=4,
        level_required=5,
        requires=Stats(endurance=13),
        price=80,
        for_classes=(TANK, WARRIOR),
    ),
    Item(
        "track_pants",
        "Спортивки",
        Slot.PANTS,
        "🩳",
        agility=1,
        image=f"{ITEM_ART}/Tracksuit_bottoms_game_icon_202608281512.jpeg",
        hp=4,
        armor_min=1,
        armor_max=2,
        dodge=0.03,
        level_required=5,
        requires=Stats(agility=13),
        price=80,
        for_classes=(ROGUE,),
    ),
    Item(
        "leather_bracers",
        "Кожаные наручи",
        Slot.GLOVES,
        "🦾",
        strength=1,
        image=f"{ITEM_ART}/Leather_forearm_bracers_icon_202608281513.jpeg",
        accuracy=0.04,
        level_required=5,
        requires=Stats(strength=13),
        price=80,
        for_classes=(WARRIOR, TANK),
    ),
    Item(
        "dealer_bracers",
        "Наручи шулера",
        Slot.GLOVES,
        "🃏",
        intuition=1,
        image=f"{ITEM_ART}/Leather_dealer_cuffs_icon_202608281515.jpeg",
        hp=4,
        anticrit=0.04,
        level_required=5,
        requires=Stats(intuition=13),
        price=80,
        for_classes=(ASSASSIN,),
    ),
    Item(
        "buckle_belt",
        "Ремень с бляхой",
        Slot.BELT,
        "🥋",
        strength=1,
        image=f"{ITEM_ART}/Leather_belt_game_inventory_icon_202608281513.jpeg",
        armor_min=2,
        armor_max=3,
        level_required=5,
        requires=Stats(strength=13),
        price=80,
        for_classes=(WARRIOR, TANK),
    ),
    Item(
        "sheath_belt",
        "Пояс с ножнами",
        Slot.BELT,
        "🗡",
        intuition=1,
        image=f"{ITEM_ART}/Leather_belt_game_inventory_icon_202608281513%20(1).jpeg",
        armor_min=1,
        armor_max=2,
        crit=0.03,
        level_required=5,
        requires=Stats(intuition=13),
        price=80,
        for_classes=(ASSASSIN, ROGUE),
    ),
    Item(
        "buckler",
        "Щиток",
        Slot.OFFHAND,
        "🛡",
        kind=ItemKind.SHIELD,
        image=f"{ADDED_ART}/Game_inventory_steel_buckler_icon_202608280250.jpeg",
        agility=1,
        hp=6,
        armor_min=4,
        armor_max=7,
        dodge=0.03,
        level_required=5,
        requires=Stats(agility=13),
        price=110,
        for_classes=(ROGUE, WARRIOR, TANK),
    ),
    # ---------- 6 уровень: оружие, головные уборы, обувь ----------
    Item(
        "bat",
        "Бита",
        Slot.WEAPON,
        "🏏",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Bat_game_inventory_icon_202608280129.jpeg",
        instrumental="битой",
        strength=2,
        damage_min=7,
        damage_max=11,
        accuracy=0.04,
        level_required=6,
        requires=Stats(strength=16),
        price=180,
        for_classes=(WARRIOR,),
    ),
    Item(
        "machete",
        "Гладиус",
        Slot.WEAPON,
        "🗡",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Roman_gladius_game_icon_202608280153.jpeg",
        instrumental="гладиусом",
        agility=2,
        damage_min=7,
        damage_max=11,
        dodge=0.04,
        level_required=6,
        requires=Stats(agility=16),
        price=180,
        for_classes=(ROGUE,),
    ),
    Item(
        "stiletto",
        "Стилет",
        Slot.WEAPON,
        "🪡",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Stiletto_game_inventory_icon_202608280134.jpeg",
        instrumental="стилетом",
        intuition=2,
        damage_min=4,
        damage_max=14,
        crit=0.04,
        level_required=6,
        requires=Stats(intuition=16),
        price=180,
        for_classes=(ASSASSIN,),
    ),
    Item(
        "sledge",
        "Кувалда",
        Slot.WEAPON,
        "🔨",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Sledgehammer_game_inventory_icon_202608280138.jpeg",
        instrumental="кувалдой",
        damage_min=8,
        damage_max=10,
        accuracy=0.04,
        anticrit=0.04,
        level_required=6,
        requires=Stats(endurance=16),
        price=180,
        for_classes=(TANK,),
    ),
    Item(
        "moto_helmet",
        "Мотошлем",
        Slot.HEAD,
        "🪖",
        hp=14,
        image=f"{ITEM_ART}/Scuffed_motorcycle_helmet_game_icon_202608281513.jpeg",
        armor_min=3,
        armor_max=5,
        anticrit=0.05,
        level_required=6,
        requires=Stats(endurance=15),
        price=100,
        for_classes=(TANK, WARRIOR),
    ),
    Item(
        "visor_cap",
        "Кепка с козырьком",
        Slot.HEAD,
        "🧢",
        intuition=2,
        image=f"{ITEM_ART}/Cap_game_inventory_icon_202608281513.jpeg",
        hp=4,
        armor_min=1,
        armor_max=2,
        crit=0.04,
        level_required=6,
        requires=Stats(intuition=15),
        price=100,
        for_classes=(ASSASSIN, ROGUE),
    ),
    Item(
        "army_boots",
        "Берцы",
        Slot.BOOTS,
        "🥾",
        hp=6,
        image=f"{ITEM_ART}/Combat_boots_game_inventory_icon_202608281512.jpeg",
        armor_min=2,
        armor_max=4,
        level_required=6,
        requires=Stats(endurance=15),
        price=100,
        for_classes=(WARRIOR, TANK),
    ),
    Item(
        "runners",
        "Беговые кроссовки",
        Slot.BOOTS,
        "👟",
        agility=2,
        image=f"{ITEM_ART}/Worn_trainers_game_inventory_icon_202608281511.jpeg",
        hp=4,
        armor_min=1,
        armor_max=2,
        dodge=0.04,
        level_required=6,
        requires=Stats(agility=15),
        price=100,
        for_classes=(ROGUE, ASSASSIN),
    ),
    Item(
        "rashguard",
        "Компрессионная футболка",
        Slot.SHIRT,
        "🥋",
        agility=1,
        image=art.shirt("rashguard"),
        dodge=0.04,
        level_required=6,
        requires=Stats(agility=15),
        price=100,
        for_classes=(ROGUE, ASSASSIN),
    ),
    # ---------- 7 уровень: оружие, перчатки, щиты ----------
    Item(
        "fire_axe",
        "Уличный топор",
        Slot.WEAPON,
        "🪓",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Customized_street_axe_game_icon_202608280139.jpeg",
        instrumental="топором",
        strength=2,
        damage_min=9,
        damage_max=16,
        accuracy=0.05,
        level_required=7,
        requires=Stats(strength=18),
        price=240,
        for_classes=(WARRIOR,),
    ),
    Item(
        "balisong",
        "Балисонг",
        Slot.WEAPON,
        "🦋",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Butterfly_knife_game_inventory_icon_202608280133.jpeg",
        instrumental="балисонгом",
        agility=2,
        damage_min=9,
        damage_max=16,
        dodge=0.05,
        level_required=7,
        requires=Stats(agility=18),
        price=240,
        for_classes=(ROGUE,),
    ),
    Item(
        "ice_pick",
        "Керамбит",
        Slot.WEAPON,
        "🪝",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Karambit_knife_game_icon_202608280141.jpeg",
        instrumental="керамбитом",
        intuition=2,
        damage_min=5,
        damage_max=20,
        crit=0.05,
        level_required=7,
        requires=Stats(intuition=18),
        price=240,
        for_classes=(ASSASSIN,),
    ),
    Item(
        "chain",
        "Цепь с замком",
        Slot.WEAPON,
        "⛓",
        kind=ItemKind.WEAPON,
        image=f"{ADDED_ART}/Bicycle_chain_and_padlock_icon_202608280249.jpeg",
        instrumental="цепью",
        damage_min=11,
        damage_max=14,
        accuracy=0.05,
        anticrit=0.05,
        level_required=7,
        requires=Stats(endurance=18),
        price=240,
        for_classes=(TANK,),
    ),
    Item(
        "battered_gloves",
        "Битые перчатки",
        Slot.GLOVES,
        "🥊",
        strength=2,
        image=f"{ITEM_ART}/Leather_fighting_gloves_game_icon_202608281512.jpeg",
        accuracy=0.06,
        level_required=7,
        requires=Stats(strength=17),
        price=130,
        for_classes=(WARRIOR, TANK),
    ),
    Item(
        "fingerless_gloves",
        "Перчатки без пальцев",
        Slot.GLOVES,
        "🧤",
        agility=2,
        image=f"{ITEM_ART}/Fingerless_gloves_game_icon_202608281512.jpeg",
        hp=4,
        dodge=0.05,
        level_required=7,
        requires=Stats(agility=17),
        price=130,
        for_classes=(ROGUE,),
    ),
    Item(
        "card_gloves",
        "Перчатки крупье",
        Slot.GLOVES,
        "🎴",
        intuition=2,
        image=f"{ITEM_ART}/Croupier_gloves_game_inventory_icon_202608281512.jpeg",
        hp=4,
        crit=0.05,
        level_required=7,
        requires=Stats(intuition=17),
        price=130,
        for_classes=(ASSASSIN,),
    ),
    Item(
        "road_sign",
        "Дорожный знак",
        Slot.OFFHAND,
        "🚧",
        kind=ItemKind.SHIELD,
        image=f"{ADDED_ART}/Shield_made_from_road_sign_202608280250.jpeg",
        hp=22,
        armor_min=7,
        armor_max=11,
        anticrit=0.06,
        level_required=7,
        requires=Stats(strength=15, endurance=17),
        price=160,
        for_classes=(TANK,),
    ),
    # ---------- 8 уровень: последнее оружие ----------
    Item(
        "cleaver",
        "Тесак",
        Slot.WEAPON,
        "⚔",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Butcher_cleaver_game_icon_202608280140.jpeg",
        instrumental="тесаком",
        strength=3,
        damage_min=13,
        damage_max=21,
        accuracy=0.07,
        level_required=8,
        requires=Stats(strength=20),
        price=300,
        for_classes=(WARRIOR,),
    ),
    Item(
        "razor",
        "Парные ножи",
        Slot.WEAPON,
        "✂️",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Crossed_street_knives_game_icon_202608280148.jpeg",
        instrumental="парными ножами",
        agility=3,
        damage_min=13,
        damage_max=21,
        dodge=0.06,
        level_required=8,
        requires=Stats(agility=20),
        price=300,
        for_classes=(ROGUE,),
    ),
    Item(
        "needle",
        "Тактический нож",
        Slot.WEAPON,
        "🔪",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Tactical_knife_game_inventory_icon_202608280151.jpeg",
        instrumental="тактическим ножом",
        intuition=3,
        damage_min=7,
        damage_max=27,
        crit=0.06,
        level_required=8,
        requires=Stats(intuition=20),
        price=300,
        for_classes=(ASSASSIN,),
    ),
    Item(
        "pry_bar",
        "Лом",
        Slot.WEAPON,
        "🦯",
        kind=ItemKind.WEAPON,
        image=f"{ADDED_ART}/Forged_steel_pry_bar_icon_202608280249.jpeg",
        instrumental="ломом",
        damage_min=15,
        damage_max=19,
        accuracy=0.07,
        anticrit=0.06,
        level_required=8,
        requires=Stats(endurance=20),
        price=300,
        for_classes=(TANK,),
    ),
    Item(
        "katana",
        "Катана",
        Slot.WEAPON,
        "🗡",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Katana_game_inventory_icon_202608280154.jpeg",
        instrumental="катаной",
        strength=2,
        damage_min=12,
        damage_max=22,
        level_required=8,
        requires=Stats(strength=18),
        price=260,
        for_classes=(WARRIOR, ROGUE),
    ),
    Item(
        "greatsword",
        "Двуручный меч",
        Slot.WEAPON,
        "⚔️",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Two-handed_sword_game_icon_202608280159.jpeg",
        instrumental="двуручным мечом",
        strength=3,
        damage_min=15,
        damage_max=19,
        level_required=8,
        requires=Stats(strength=20),
        price=270,
        for_classes=(WARRIOR, TANK),
    ),
    Item(
        "kevlar_tee",
        "Кевларовая футболка",
        Slot.SHIRT,
        "🦺",
        hp=8,
        image=art.shirt("kevlar_tee"),
        level_required=8,
        anticrit=0.05,
        requires=Stats(endurance=20),
        price=140,
        for_classes=(TANK, WARRIOR),
    ),
    Item(
        "riot_shield",
        "Штурмовой щит",
        Slot.OFFHAND,
        "🛡",
        kind=ItemKind.SHIELD,
        hp=20,
        armor_min=10,
        armor_max=15,
        anticrit=0.08,
        level_required=8,
        requires=Stats(strength=18, endurance=20),
        price=220,
        for_classes=(TANK, WARRIOR),
    ),
    # ---------- 9 уровень: чем добивают на потолке ----------
    # До этой ступени доходят единицы, поэтому цена кусается, а требования
    # рассчитаны на развитый билд своего класса, а не на универсала.
    Item(
        "viking_axe",
        "Секира викинга",
        Slot.WEAPON,
        "🪓",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Viking_battle_axe_game_icon_202608280222.jpeg",
        instrumental="секирой",
        strength=4,
        damage_min=17,
        damage_max=25,
        accuracy=0.08,
        level_required=9,
        requires=Stats(strength=22),
        price=400,
        for_classes=(WARRIOR,),
    ),
    Item(
        "nail_bat",
        "Бита с гвоздями",
        Slot.WEAPON,
        "🏏",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Game_inventory_icon_of_bat_202608280221.jpeg",
        instrumental="битой",
        strength=2,
        agility=2,
        damage_min=16,
        damage_max=26,
        dodge=0.07,
        level_required=9,
        requires=Stats(agility=22),
        price=400,
        for_classes=(ROGUE,),
    ),
    Item(
        "shiv",
        "Заточка",
        Slot.WEAPON,
        "📌",
        kind=ItemKind.WEAPON,
        image=f"{ADDED_ART}/Shiv_game_inventory_icon_202608280250.jpeg",
        instrumental="заточкой",
        intuition=4,
        damage_min=9,
        damage_max=33,
        crit=0.08,
        level_required=9,
        requires=Stats(intuition=22),
        price=400,
        for_classes=(ASSASSIN,),
    ),
    Item(
        "splitting_axe",
        "Колун",
        Slot.WEAPON,
        "🪵",
        kind=ItemKind.WEAPON,
        image=f"{WEAPON_ART}/Splitting_axe_game_inventory_icon_202608280223.jpeg",
        instrumental="колуном",
        strength=3,
        damage_min=19,
        damage_max=23,
        accuracy=0.08,
        anticrit=0.07,
        level_required=9,
        requires=Stats(endurance=24),
        price=400,
        for_classes=(TANK,),
    ),
    # ---------- награды: их не покупают, их выдают ----------
    # Стилету не нашлось ступени на прилавке: на пятом уровне оружия нет
    # вовсе, а на четвёртом и шестом у ассасина уже есть своё — шило и
    # стилет. Дать ему числа между ступенями значит выдать ассасину целый
    # тир форы над всеми, кто в это время ходит с оружием своего уровня
    # (круг классов на пятом уровне на этом и ломался). Поэтому он не
    # товар, а награда: приходит вместе с подпиской, как и клинок.
    Item(
        "assassin_stiletto",
        "Стилет ассасина",
        Slot.WEAPON,
        "🗡️",
        kind=ItemKind.WEAPON,
        instrumental="стилетом",
        intuition=1,
        damage_min=3,
        damage_max=11,
        crit=0.05,
        accuracy=0.05,
        level_required=5,
        reward=True,
        for_classes=(ASSASSIN,),
    ),
    Item(
        "hidden_blade",
        "Клинок ассасина",
        Slot.WEAPON,
        "🗡",
        kind=ItemKind.WEAPON,
        instrumental="скрытым клинком",
        image=f"{WEAPON_ART}/Concealed_blade_game_inventory_icon_202608291031.jpeg",
        intuition=2,
        damage_min=3,
        damage_max=9,
        crit=0.15,
        level_required=1,
        requires=Stats(intuition=7),
        reward=True,
        for_classes=(ASSASSIN,),
    ),
    # ---------- стенд: вещи с ручными числами ----------
    # Их числа нарочно выше потолка — на них руками проверяют, как эффекты
    # ведут себя в бою. Поэтому они награды: на прилавок не попадают, в
    # эталонный комплект не идут и в балансе не участвуют. Выдаются
    # адресно тестовым бойцам (bot.seed).
    Item(
        "test_wraps",
        "Бинты (стенд)",
        Slot.GLOVES,
        "🩹",
        strength=5,
        image=f"{ITEM_ART}/Hand_wraps_game_inventory_icon_202608281513.jpeg",
        accuracy=0.05,
        dodge=0.15,
        counter=0.15,
        requires=Stats(strength=4),
        reward=True,
        for_classes=(WARRIOR, TANK),
    ),
    Item(
        "test_bandana",
        "Бандана (стенд)",
        Slot.HEAD,
        "🧢",
        intuition=5,
        image=f"{ITEM_ART}/bandana.jpeg_202608281514.jpeg",
        armor_min=0,
        armor_max=1,
        crit=0.35,
        anticrit=0.25,
        requires=Stats(intuition=4),
        reward=True,
        for_classes=(ASSASSIN,),
    ),
    Item(
        "test_sneakers",
        "Кеды (стенд)",
        Slot.BOOTS,
        "👟",
        image=f"{ITEM_ART}/sneakers.jpeg",
        agility=5,
        armor_min=0,
        armor_max=1,
        dodge=0.15,
        crit=0.15,
        level_required=2,
        requires=Stats(agility=5),
        reward=True,
        for_classes=(ROGUE,),
    ),
    Item(
        "test_shirt",
        "Майка-алкоголичка (стенд)",
        Slot.SHIRT,
        "🎽",
        strength=3,
        agility=3,
        intuition=3,
        hp=60,
        image=art.shirt("wife_beater"),
        reward=True,
    ),
    # ---------- фанатский магазин «Северный Вал»: экипировка своей команды ----------
    #
    # Отдельный прилавок, а не следующая ступень клубной лавки. Вещи тут
    # десятого уровня и от тысячи кредитов — это десять уровней дохода за
    # одну вещь, поэтому в эталонный комплект они не идут: эталон — это
    # осмысленно одетый боец, а не тот, кто копил семь тысяч. Числа при
    # этом держатся в тех же потолках, что и витрина клуба: +4 плоских и
    # 10% — выше них ломается круг классов.
    #
    # Линий три, по фанатским ролям: тяжёлая «босса», средняя «воина» и
    # лёгкая техничная. Лёгкую носят и ассасин, и трикстер, поэтому
    # надевается она по выносливости — ловкость с интуицией у этих двоих
    # разные, и общее требование отсекло бы одного из них.
    Item(
        "fan_boss_bat",
        "Бита с гвоздями",
        Slot.WEAPON,
        "🔨",
        kind=ItemKind.WEAPON,
        instrumental="битой с гвоздями",
        strength=3,
        damage_min=22,
        damage_max=28,
        accuracy=0.08,
        anticrit=0.07,
        level_required=10,
        requires=Stats(strength=15, endurance=26),
        price=1600,
        for_classes=(TANK,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_boss_shield",
        "Щит фанатского сектора",
        Slot.OFFHAND,
        "🛡",
        kind=ItemKind.SHIELD,
        hp=24,
        armor_min=12,
        armor_max=16,
        anticrit=0.09,
        level_required=10,
        requires=Stats(strength=15, endurance=24),
        price=1400,
        for_classes=(TANK, WARRIOR),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_boss_polo",
        "Плотное поло",
        Slot.SHIRT,
        "👕",
        hp=10,
        anticrit=0.06,
        level_required=10,
        requires=Stats(endurance=24),
        price=1000,
        for_classes=(TANK,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_boss_jacket",
        "Тяжёлая полевая куртка",
        Slot.JACKET,
        "🧥",
        hp=18,
        armor_min=4,
        armor_max=6,
        anticrit=0.04,
        level_required=10,
        requires=Stats(endurance=24),
        price=1500,
        for_classes=(TANK,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_boss_track_pants",
        "Плотные спортивные штаны",
        Slot.PANTS,
        "👖",
        hp=8,
        armor_min=3,
        armor_max=5,
        level_required=10,
        requires=Stats(endurance=22),
        price=1100,
        for_classes=(TANK,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_boss_sneakers",
        "Замшевые террас-кроссовки",
        Slot.BOOTS,
        "👟",
        hp=8,
        armor_min=3,
        armor_max=4,
        level_required=10,
        requires=Stats(endurance=22),
        price=1100,
        for_classes=(TANK,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_boss_cap",
        "Кепка фанатского сектора",
        Slot.HEAD,
        "🧢",
        hp=16,
        armor_min=3,
        armor_max=5,
        anticrit=0.06,
        level_required=10,
        requires=Stats(endurance=24),
        price=1200,
        for_classes=(TANK,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_boss_belt",
        "Широкий кожаный пояс",
        Slot.BELT,
        "🥋",
        strength=2,
        hp=4,
        armor_min=2,
        armor_max=4,
        level_required=10,
        requires=Stats(strength=14, endurance=20),
        price=1000,
        for_classes=(TANK,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_warrior_bat",
        "Бейсбольная бита",
        Slot.WEAPON,
        "🏏",
        kind=ItemKind.WEAPON,
        instrumental="бейсбольной битой",
        strength=4,
        damage_min=19,
        damage_max=31,
        accuracy=0.08,
        level_required=10,
        requires=Stats(strength=24),
        price=1500,
        for_classes=(WARRIOR,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_warrior_tee",
        "Спортивная футболка",
        Slot.SHIRT,
        "🎽",
        strength=1,
        hp=10,
        counter=0.03,
        level_required=10,
        requires=Stats(strength=20),
        price=1000,
        for_classes=(WARRIOR,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_warrior_harrington",
        "Куртка-харрингтон",
        Slot.JACKET,
        "🧥",
        strength=1,
        hp=16,
        armor_min=3,
        armor_max=5,
        level_required=10,
        requires=Stats(strength=22),
        price=1400,
        for_classes=(WARRIOR,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_warrior_track_pants",
        "Спортивные штаны",
        Slot.PANTS,
        "👖",
        hp=10,
        armor_min=3,
        armor_max=4,
        level_required=10,
        requires=Stats(strength=20),
        price=1100,
        for_classes=(WARRIOR,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_warrior_sneakers",
        "Массивные ретро-кроссовки",
        Slot.BOOTS,
        "👟",
        hp=8,
        armor_min=2,
        armor_max=4,
        counter=0.04,
        level_required=10,
        requires=Stats(strength=20),
        price=1100,
        for_classes=(WARRIOR,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_warrior_cap",
        "Ретро-спортивная кепка",
        Slot.HEAD,
        "🧢",
        strength=1,
        hp=10,
        armor_min=3,
        armor_max=4,
        accuracy=0.03,
        level_required=10,
        requires=Stats(strength=20),
        price=1200,
        for_classes=(WARRIOR,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_warrior_belt",
        "Тканевый спортивный пояс",
        Slot.BELT,
        "🥋",
        strength=1,
        hp=6,
        armor_min=2,
        armor_max=3,
        level_required=10,
        requires=Stats(strength=20),
        price=1000,
        for_classes=(WARRIOR,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_assassin_knife",
        "Складной нож",
        Slot.WEAPON,
        "🔪",
        kind=ItemKind.WEAPON,
        instrumental="складным ножом",
        intuition=4,
        damage_min=11,
        damage_max=39,
        crit=0.08,
        level_required=10,
        requires=Stats(intuition=20),
        price=1500,
        for_classes=(ASSASSIN,),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_assassin_polo",
        "Техническое поло",
        Slot.SHIRT,
        "👕",
        agility=1,
        hp=8,
        dodge=0.04,
        level_required=10,
        requires=Stats(endurance=18),
        price=1000,
        for_classes=(ASSASSIN, ROGUE),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_assassin_track_jacket",
        "Лёгкая спортивная куртка",
        Slot.JACKET,
        "🧥",
        agility=1,
        intuition=1,
        armor_min=2,
        armor_max=4,
        dodge=0.04,
        hp=10,
        level_required=10,
        requires=Stats(endurance=18),
        price=1400,
        for_classes=(ASSASSIN, ROGUE),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_assassin_track_pants",
        "Зауженные технические штаны",
        Slot.PANTS,
        "👖",
        agility=1,
        armor_min=1,
        armor_max=3,
        dodge=0.04,
        hp=6,
        level_required=10,
        requires=Stats(endurance=18),
        price=1100,
        for_classes=(ASSASSIN, ROGUE),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_assassin_sneakers",
        "Лёгкие беговые кроссовки",
        Slot.BOOTS,
        "👟",
        agility=2,
        hp=6,
        armor_min=1,
        armor_max=2,
        dodge=0.05,
        level_required=10,
        requires=Stats(endurance=18),
        price=1100,
        for_classes=(ASSASSIN, ROGUE),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_assassin_cap",
        "Техническая кепка",
        Slot.HEAD,
        "🧢",
        intuition=2,
        hp=6,
        armor_min=1,
        armor_max=2,
        crit=0.05,
        level_required=10,
        requires=Stats(endurance=18),
        price=1200,
        for_classes=(ASSASSIN, ROGUE),
        shelf=FAN_SHELF,
    ),
    Item(
        "fan_assassin_belt",
        "Компактный тактический пояс",
        Slot.BELT,
        "🥋",
        intuition=1,
        armor_min=1,
        armor_max=2,
        crit=0.04,
        counter=0.04,
        level_required=10,
        requires=Stats(endurance=18),
        price=1000,
        for_classes=(ASSASSIN, ROGUE),
        shelf=FAN_SHELF,
    ),
    # ---------- лавка мага: только за звёзды ----------
    Item(
        "lightsaber",
        "Световой меч",
        Slot.WEAPON,
        "🗡",
        kind=ItemKind.WEAPON,
        instrumental="световым мечом",
        # У мага картинка лежит в png: у клинка есть свечение по краям
        image=f"{MAGIC_ART}/lightsaber.png",
        intuition=5,
        damage_min=7,
        damage_max=15,
        dodge=0.35,
        counter=0.25,
        level_required=2,
        requires=Stats(strength=10),
        stars=250,
    ),
)

CATALOGUE: dict[str, Item] = {item.code: item for item in ITEMS}

# Витрина лавки клуба: по типам вещей в порядке слотов карточки, внутри — от
# простого к дорогому. Вещи из лавки мага сюда не попадают: за кредиты их не
# купить, и висеть на прилавке рядом с кастетом им незачем.
SHOWCASE: tuple[Item, ...] = tuple(
    sorted(
        (item for item in ITEMS if not item.is_magic and item.on_sale and not item.shelf),
        key=lambda item: (ALL_SLOTS.index(item.slot), item.level_required, item.price),
    )
)

# Прилавок фанатского магазина: та же раскладка по слотам, но свой товар.
# В витрину клуба он не входит — и потому не тянет за собой ни лестницу
# цен, ни правило «никто не отстаёт больше чем на три уровня»
FAN_ITEMS: tuple[Item, ...] = tuple(
    sorted(
        (item for item in ITEMS if item.shelf == FAN_SHELF and item.on_sale),
        key=lambda item: (ALL_SLOTS.index(item.slot), item.level_required, item.price),
    )
)

# Прилавок мага: только за звёзды
MAGIC_ITEMS: tuple[Item, ...] = tuple(
    sorted(
        (item for item in ITEMS if item.is_magic and item.on_sale),
        key=lambda item: item.stars,
    )
)


def shelf_of(shelf: str = "") -> tuple[Item, ...]:
    """Товар названного прилавка: пусто — клубная витрина."""
    return FAN_ITEMS if shelf == FAN_SHELF else SHOWCASE


def shop_sections(shelf: str = "") -> list[tuple[Slot, tuple[Item, ...]]]:
    """Товары, разложенные по типам — так магазин и показывает их."""
    goods = shelf_of(shelf)
    return [
        (slot, tuple(item for item in goods if item.slot is slot))
        for slot in ALL_SLOTS
    ]


def items_unlocked_at(level: int) -> tuple[Item, ...]:
    """Что открывается ровно на этом уровне."""
    return tuple(item for item in SHOWCASE if item.level_required == level)


def get_item(code: str) -> Item | None:
    return CATALOGUE.get(code)
